parameters:
    app.template_dir: %kernel.root_dir%/../templates/

services:
    phlexible_template.loader:
        class: Phlexible\Bundle\TemplateBundle\TemplateLoader
        arguments: [%app.template_dir%]

    phlexible_template.repository:
        class: Phlexible\Bundle\TemplateBundle\TemplateRepository
        arguments: [@phlexible_template.loader]

    # acl providers
    phlexible_template.acl_provider:
        class: Phlexible\Bundle\TemplateBundle\AclProvider\TemplateAclProvider
        public: false
        tags:
            - {name: phlexible_security.acl.provider}

    # asset providers
    phlexible_template.asset_provider:
        class: Phlexible\Bundle\TemplateBundle\AssetProvider\TemplateAssetProvider
        public: false
        arguments: [@file_locator]
        tags:
            - {name: phlexible_gui.asset.provider}
