services:
    phlexible_media_asset.reader.attribute.exif_extension:
        class: Phlexible\Bundle\MediaAssetBundle\AttributeReader\ExifExtensionAttributeReader
        public: false
        tags:
            - {name: phlexible_media_asset.attribute_reader}

    phlexible_media_asset.reader.attribute.getid3:
        class: Phlexible\Bundle\MediaAssetBundle\AttributeReader\GetId3AttributeReader
        public: false
        tags:
            - {name: phlexible_media_asset.attribute_reader}

    phlexible_media_asset.reader.attribute.imageanalyzer:
        class: Phlexible\Bundle\MediaAssetBundle\AttributeReader\ImageAnalyzerAttributeReader
        public: false
        arguments: [@phlexible_media_tool.image_analyzer]
        tags:
            - {name: phlexible_media_asset.attribute_reader}

    phlexible_media_asset.reader.attribute.pdfinfo:
        class: Phlexible\Bundle\MediaAssetBundle\AttributeReader\PdfInfoAttributeReader
        public: false
        arguments: [@phlexible_media_tool.pdfinfo]
        tags:
            - {name: phlexible_media_asset.attribute_reader}

    phlexible_media_asset.reader.attribute.videoanalyzer:
        class: Phlexible\Bundle\MediaAssetBundle\AttributeReader\VideoAnalyzerAttributeReader
        public: false
        arguments: [@phlexible_media_tool.ffprobe, @logger]
        tags:
            - {name: phlexible_media_asset.attribute_reader}
            - {name: monolog.logger, channel: media_asset}

    phlexible_media_asset.reader.attribute.zipextension:
        class: Phlexible\Bundle\MediaAssetBundle\AttributeReader\ZipExtensionAttributeReader
        public: false
        tags:
            - {name: phlexible_media_asset.attribute_reader}

    phlexible_media_asset.reader.attribute:
        class: Phlexible\Bundle\MediaAssetBundle\AttributeReader\ChainAttributeReader
        arguments: [[]]
