services:
    phlexible_media_asset.extractor.audio.raw:
        class: Phlexible\Bundle\MediaAssetBundle\AudioExtractor\RawAudioExtractor
        public: false
        tags:
            - {name: phlexible_media_asset.audio_extractor}
