services:
    phlexible_media_asset.extractor.content.pdftotext:
        class: Phlexible\Bundle\MediaAssetBundle\ContentExtractor\PdfToTextExtractor
        public: false
        arguments: [@phlexible_media_tool.pdftotext]
        tags:
            - {name: phlexible_media_asset.content_extractor}

    phlexible_media_asset.extractor.content.rawtext:
        class: Phlexible\Bundle\MediaAssetBundle\ContentExtractor\RawTextExtractor
        public: false
        tags:
            - {name: phlexible_media_asset.content_extractor}

    phlexible_media_asset.extractor.content.zendlucenedocx:
        class: Phlexible\Bundle\MediaAssetBundle\ContentExtractor\ZendLuceneDocxExtractor
        public: false
        tags:
            - {name: phlexible_media_asset.content_extractor}

    phlexible_media_asset.extractor.content.zendlucenepptx:
        class: Phlexible\Bundle\MediaAssetBundle\ContentExtractor\ZendLucenePptxExtractor
        public: false
        tags:
            - {name: phlexible_media_asset.content_extractor}

    phlexible_media_asset.extractor.content.zendlucenexlsx:
        class: Phlexible\Bundle\MediaAssetBundle\ContentExtractor\ZendLuceneXlsxExtractor
        public: false
        tags:
            - {name: phlexible_media_asset.content_extractor}

    phlexible_media_asset.extractor.content.resolver:
        class: Phlexible\Bundle\MediaAssetBundle\ContentExtractor\ContentExtractorResolver
        public: false
        arguments:
            -
                - @phlexible_media_asset.extractor.content.pdftotext
                - @phlexible_media_asset.extractor.content.rawtext
                - @phlexible_media_asset.extractor.content.zendlucenedocx
                - @phlexible_media_asset.extractor.content.zendlucenepptx
                - @phlexible_media_asset.extractor.content.zendlucenexlsx

    phlexible_media_asset.extractor.content:
        class: Phlexible\Bundle\MediaAssetBundle\ContentExtractor\DelegatingContentExtractor
        arguments: [@phlexible_media_asset.extractor.content.resolver]
