services:
    phlexible_media_asset.extractor.image.video_converter:
        class: Phlexible\Bundle\MediaAssetBundle\ImageExtractor\VideoConverterImageExtractor
        public: false
        arguments: [@phlexible_media_tool.ffmpeg, %phlexible_media_asset.asset_temp_dir%]
        tags:
            - {name: phlexible_media_asset.image_extractor}

    phlexible_media_asset.extractor.image.getid3:
        class: Phlexible\Bundle\MediaAssetBundle\ImageExtractor\GetId3ImageExtractor
        public: false
        arguments: [%phlexible_media_asset.asset_temp_dir%, @logger]
        tags:
            - {name: phlexible_media_asset.image_extractor}
            - {name: monolog.logger, channel: media_asset}

    phlexible_media_asset.extractor.image.raw:
        class: Phlexible\Bundle\MediaAssetBundle\ImageExtractor\RawImageExtractor
        public: false
        tags:
            - {name: phlexible_media_asset.image_extractor}
