services:
    phlexible_media_asset.reader.meta.exif_extension:
        class: Phlexible\Bundle\MediaAssetBundle\MetaReader\ExifExtensionMetaReader
        public: false
        tags:
            - {name: phlexible_media_asset.meta_reader}

    phlexible_media_asset.reader.meta.id3_extension:
        class: Phlexible\Bundle\MediaAssetBundle\MetaReader\Id3ExtensionMetaReader
        public: false
        tags:
            - {name: phlexible_media_asset.meta_reader}

    phlexible_media_asset.reader.meta.open_xml:
        class: Phlexible\Bundle\MediaAssetBundle\MetaReader\OpenXmlMetaReader
        public: false
        tags:
            - {name: phlexible_media_asset.meta_reader}

    phlexible_media_asset.reader.meta.zend_media:
        class: Phlexible\Bundle\MediaAssetBundle\MetaReader\ZendMediaMetaReader
        public: false
        arguments: [@logger]
        tags:
            - {name: phlexible_media_asset.meta_reader}
            - {name: monolog.logger, channel: media_asset}

    phlexible_media_asset.reader.meta.zend_pdf:
        class: Phlexible\Bundle\MediaAssetBundle\MetaReader\ZendPdfMetaReader
        public: false
        tags:
            - {name: phlexible_media_asset.meta_reader}

    phlexible_media_asset.reader.meta.zip_extension:
        class: Phlexible\Bundle\MediaAssetBundle\MetaReader\ZipExtensionMetaReader
        public: false
        tags:
            - {name: phlexible_media_asset.meta_reader}

    phlexible_media_asset.reader.meta.resolver:
        class: Phlexible\Bundle\MediaAssetBundle\MetaReader\MetaReaderResolver
        public: false
        arguments:
            - @phlexible_media_asset.reader.meta.exif_extension
            - @phlexible_media_asset.reader.meta.id3_extension
            - @phlexible_media_asset.reader.meta.open_xml
            - @phlexible_media_asset.reader.meta.zend_media
            - @phlexible_media_asset.reader.meta.zend_pdf
            - @phlexible_media_asset.reader.meta.zip_extension

    phlexible_media_asset.reader.meta:
        class: Phlexible\Bundle\MediaAssetBundle\MetaReader\DelegatingMetaReader
        arguments: [@phlexible_media_asset.reader.meta.resolver]
