parameters:
    phlexible_media_asset.asset_temp_dir: %kernel.cache_dir%/mediaasset/temp/

services:
    phlexible_media_asset.transmutor:
        class: Phlexible\Bundle\MediaAssetBundle\Transmutor
        arguments:
            - [@phlexible_media_asset.extractor.image.video_converter, @phlexible_media_asset.extractor.image.zend_media, @phlexible_media_asset.extractor.image.raw]
            - [@phlexible_media_asset.extractor.video.raw]
            - [@phlexible_media_asset.extractor.audio.raw]
            - [@phlexible_media_asset.extractor.flash.raw]

    # event listeners
    phlexible_media_asset.listener.file:
        class: Phlexible\Bundle\MediaAssetBundle\EventListener\FileListener
        arguments: [@phlexible_media_asset.reader.attribute, @phlexible_media_asset.reader.meta]
        tags:
            - {name: kernel.event_listener, event: phlexible_media_site.before_create_file, method: onBeforeCreateFile}
