parameters:
    phlexible_media_asset.asset_temp_dir: %kernel.cache_dir%/mediaasset/temp/

services:
    # event listeners
    phlexible_media_asset.listener.file:
        class: Phlexible\Bundle\MediaAssetBundle\EventListener\FileListener
        arguments: [@phlexible_media_asset.reader.attribute]
        tags:
            - {name: kernel.event_listener, event: phlexible_media_site.before_create_file, method: onBeforeCreateFile}
