parameters:
    phlexible_media_asset.asset_temp_dir: %kernel.cache_dir%/mediaasset/temp/

services:
    # event listeners
    phlexible_media_asset.listener.media_site:
        class: Phlexible\Bundle\MediaAssetBundle\EventListener\MediaSiteListener
        arguments: [@phlexible_media_asset.reader.attribute, @phlexible_media_type.media_type_manager]
        tags:
            - {name: kernel.event_subscriber}
