services:
    # twig extensions
    phlexible_element_finder.twig.extension.element_finder:
        class: Phlexible\Bundle\ElementFinderBundle\Twig\Extension\ElementFinderExtension
        public: false
        arguments:
            - @phlexible_element_finder.finder
            - @request_stack
        tags:
            - {name: twig.extension}
