services:
    phlexible_task.doctrine.task_manager:
        class: Phlexible\Bundle\TaskBundle\Doctrine\TaskManager
        public: false
        arguments:
            - @doctrine.orm.entity_manager
            - @phlexible_task.types
            - @phlexible_task.state_machine
            - @phlexible_user.user_manager
            - @phlexible_message.message_poster
            - @phlexible_task.mailer
            - %phlexible_task.mail_on_close%
