services:
    phlexible_element_renderer.data_provider:
        class: Phlexible\Bundle\ElementRendererBundle\DataProvider\DataProvider
        arguments:
            - @phlexible_element_renderer.configurator
            - @event_dispatcher
            -
                twig: @phlexible_twig_renderer.data_provider
