services:
    phlexible_element_renderer.configurator:
        class: Phlexible\Bundle\ElementRendererBundle\Configurator\RenderConfigurator
        arguments: [@event_dispatcher, @logger, []]
        tags:
            - {name: monolog.logger, channel: element_renderer}