services:
    phlexible_element_renderer.configurator:
        class: Phlexible\Bundle\ElementRendererBundle\Configurator\ChainConfigurator
        arguments: [[]]
        tags:
            - {name: monolog.logger, channel: element_renderer}