parameters:
    phlexible_cms.languages.default: en
    phlexible_cms.languages.available: en,de

services:
    # event listeners
    phlexible_cms.listener.get_config:
        class: Phlexible\Bundle\CmsBundle\EventListener\GetConfigListener
        arguments:
            - @security.token_storage
            - %phlexible_cms.languages.default%
            - %phlexible_cms.languages.available%
        tags:
            - {name: kernel.event_listener, event: phlexible_gui.get_config, method: onGetConfig}

    # role providers
    phlexible_cms.role_provider:
        class: Phlexible\Bundle\CmsBundle\RoleProvider\CmsRoleProvider
        public: false
        tags:
            - {name: phlexible_gui.role_provider}

    # twig extensions
    phlexible_cms.twig.misc_extension:
        class: Phlexible\Bundle\CmsBundle\Twig\Extension\MiscExtension
        public: false
        tags:
            - {name: twig.extension}

    phlexible_cms.twig.text_extension:
        class: Phlexible\Bundle\CmsBundle\Twig\Extension\TextExtension
        public: false
        tags:
            - {name: twig.extension}
