parameters:
    phlexible_cms.languages.default: en
    phlexible_cms.languages.available: en,de

services:
    # event listeners
    phlexible_cms.listener.get_config:
        class: Phlexible\Bundle\CmsBundle\EventListener\GetConfigListener
        arguments:
            - @security.token_storage
            - %phlexible_cms.languages.default%
            - %phlexible_cms.languages.available%
        tags:
            - {name: kernel.event_listener, event: phlexible_gui.get_config, method: onGetConfig}

    phlexible_cms.listener.element:
        class: Phlexible\Bundle\CmsBundle\EventListener\ElementListener
        arguments: [@phlexible_cms.usage_updater]
        tags:
            - {name: kernel.event_subscriber}

    # fields
    phlexible_cms.field.folder:
        class: Phlexible\Bundle\CmsBundle\Field\FolderField
        public: false
        tags:
            - {name: phlexible_elementtype.field, alias: folder}

    phlexible_cms.field.file:
        class: Phlexible\Bundle\CmsBundle\Field\FileField
        public: false
        tags:
            - {name: phlexible_elementtype.field, alias: file}

    # problem checkers
    phlexible_cms.problem.specialtidcheck:
        class: Phlexible\Bundle\CmsBundle\ProblemChecker\SpecialTidChecker
        public: false
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - {name: problem.checker}

    # role providers
    phlexible_cms.role_provider:
        class: Phlexible\Bundle\CmsBundle\RoleProvider\CmsRoleProvider
        public: false
        tags:
            - {name: phlexible_gui.role_provider}

    # twig extensions
    phlexible_cms.twig.misc_extension:
        class: Phlexible\Bundle\CmsBundle\Twig\Extension\MiscExtension
        public: false
        tags:
            - {name: twig.extension}

    phlexible_cms.twig.text_extension:
        class: Phlexible\Bundle\CmsBundle\Twig\Extension\TextExtension
        public: false
        tags:
            - {name: twig.extension}

    phlexible_cms.twig.media_extension:
        class: Phlexible\Bundle\CmsBundle\Twig\Extension\MediaExtension
        public: false
        arguments:
            - @router
            - @phlexible_media_manager.volume_manager
            - @phlexible_media_manager.file_meta_set_resolver
            - @phlexible_media_manager.doctrine.file_meta_data_manager
        tags:
            - {name: twig.extension}
