services:
    phlexible_cms.usage_updater.file:
        class: Phlexible\Bundle\CmsBundle\Usage\FileUsageUpdater
        arguments:
            - @doctrine.orm.entity_manager
            - @phlexible_media_manager.volume_manager

    phlexible_cms.usage_updater.folder:
        class: Phlexible\Bundle\CmsBundle\Usage\FolderUsageUpdater
        arguments:
            - @doctrine.orm.entity_manager
            - @phlexible_media_manager.volume_manager

    phlexible_cms.usage_updater:
        class: Phlexible\Bundle\CmsBundle\Usage\UsageUpdater
        arguments:
            - @phlexible_cms.usage_updater.file
            - @phlexible_cms.usage_updater.folder
