services:
    # event listeners
    phlexible_queue.listener.collect_problems:
        class: Phlexible\Bundle\QueueBundle\EventListener\CollectProblemsListener
        arguments: [@properties]
        tags:
            - {name: kernel.event_listener, event: phlexible_problem.collect, method: onCollectProblems}

    phlexible_queue.listener.console:
        class: Phlexible\Bundle\QueueBundle\EventListener\ConsoleListener
        arguments: [@phlexible_queue.job_manager]
        tags:
            - {name: kernel.event_subscriber}

    # role providers
    phlexible_queue.role_provider:
        class: Phlexible\Bundle\QueueBundle\RoleProvider\QueueRoleProvider
        public: false
        tags:
            - {name: phlexible_gui.role_provider}
