parameters:
    phlexible_media_type.compiler.cache_dir: %kernel.cache_dir%/mediatype/

services:
    phlexible_media_type.icon_resolver:
        class: Phlexible\Bundle\MediaTypeBundle\Icon\IconResolver
        arguments: [@file_locator]

    phlexible_media_type.compiler.php:
        class: Phlexible\Bundle\MediaTypeBundle\Compiler\PhpCompiler
        public: false

    phlexible_media_type.compiler.css:
        class: Phlexible\Bundle\MediaTypeBundle\Compiler\CssCompiler
        public: false

    # event listeners
    phlexible_media_type.listener.view_frame:
        class: Phlexible\Bundle\MediaTypeBundle\EventListener\ViewFrameListener
        arguments: [@router]
        tags:
            - {name: kernel.event_listener, event: phlexible_gui.view_frame, method: onViewFrame}

    # role provider
    phlexible_media_type.role_provider:
        class: Phlexible\Bundle\MediaTypeBundle\RoleProvider\MediaTypeRoleProvider
        public: false
        tags:
            - {name: phlexible_gui.role_provider}
