preset: symfony

linting: true

enabled:
    - ordered_use
    - strict
    - psr4

disabled:
    - empty_return

    # Unusable at the moment
    # https://github.com/StyleCI/StyleCI/issues/471
    - psr0
