language: php

before_script:
    - composer self-update
    - composer install --no-interaction --prefer-source --dev

before_install:
    - composer self-update

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

script:
    - vendor/bin/phpunit --exclude-group functional --verbose
