services:
    phlexible_media_manager.attribute_reader.exif_extension:
        class: Temp\MetaReader\ExifExtensionReader
        public: false
        tags:
            - {name: phlexible_media_manager.attribute_reader}

    phlexible_media_manager.attribute_reader.exiftool:
        class: Temp\MetaReader\ExiftoolReader
        public: false
        arguments: [@phlexible_media.exiftool]
        tags:
            - {name: phlexible_media_manager.attribute_reader}

    phlexible_media_manager.attribute_reader.imageanalyzer:
        class: Temp\MetaReader\ImageAnalyzerReader
        public: false
        arguments: [@phlexible_media.image_analyzer]
        tags:
            - {name: phlexible_media_manager.attribute_reader}

    phlexible_media_manager.attribute_reader.pdfinfo:
        class: Temp\MetaReader\PdfInfoReader
        public: false
        arguments: [@phlexible_media.poppler.pdf_file]
        tags:
            - {name: phlexible_media_manager.attribute_reader}

    phlexible_media_manager.attribute_reader.videoanalyzer:
        class: Temp\MetaReader\FfprobeReader
        public: false
        arguments: [@phlexible_media.ffprobe]
        tags:
            - {name: phlexible_media_manager.attribute_reader}
            - {name: monolog.logger, channel: media_asset}

    phlexible_media_manager.attribute_reader.zipextension:
        class: Temp\MetaReader\ZipExtensionReader
        public: false
        tags:
            - {name: phlexible_media_manager.attribute_reader}

    phlexible_media_manager.attribute_reader:
        class: Temp\MetaReader\ChainReader
        arguments: [[]]
