services:
    phlexible_media_manager.doctrine.volume_manager:
        class: Phlexible\Component\Volume\Doctrine\VolumeManager
        arguments:
            - @doctrine.orm.entity_manager
            - @phlexible_media_manager.hash_calculator
            - @event_dispatcher
            - Phlexible\Bundle\MediaManagerBundle\Entity\Folder
            - Phlexible\Bundle\MediaManagerBundle\Entity\File
            - %phlexible_media_manager.volume_configs%

    #phlexible_media_manager.driver.doctrine:
    #    class: Phlexible\Component\Volume\Driver\DoctrineDriver
    #    scope: prototype
    #    arguments:
    #        - @doctrine.orm.entity_manager
    #        - @phlexible_media_manager.hash_calculator
    #        - Phlexible\Bundle\MediaManagerBundle\Entity\Folder
    #        - Phlexible\Bundle\MediaManagerBundle\Entity\File
