parameters:
    phlexible_media_manager.temp_dir: %kernel.cache_dir%/mediamanager/temp/
    phlexible_media_manager.portlet.style: large
    phlexible_media_manager.portlet.num_items: 20
    phlexible_media_manager.files.view: tiles
    phlexible_media_manager.files.num_files: 20
    phlexible_media_manager.upload.enable_upload_sort: true
    phlexible_media_manager.upload.disable_flash: false
    phlexible_media_manager.delete_policy: hide_old

services:
    phlexible_media_manager.file_serializer:
        class: Phlexible\Bundle\MediaManagerBundle\Serializer\FileSerializer
        arguments:
            - @phlexible_media_type.media_type_manager
            - @phlexible_media_cache.cache_manager
            - @phlexible_media_manager.file_usage_manager
            - @router

    phlexible_media_manager.folder_serializer:
        class: Phlexible\Bundle\MediaManagerBundle\Serializer\FolderSerializer
        arguments:
            - @phlexible_media_manager.folder_usage_manager

    phlexible_media_manager.delete_file_checker:
        class: Phlexible\Component\MediaManager\Volume\DeleteFileChecker
        arguments:
            - @doctrine.orm.entity_manager
            - @security.authorization_checker
            - %phlexible_media_manager.delete_policy%

    phlexible_media_manager.delete_folder_checker:
        class: Phlexible\Component\MediaManager\Volume\DeleteFolderChecker
        arguments:
            - @doctrine.orm.entity_manager
            - @security.authorization_checker
            - %phlexible_media_manager.delete_policy%

    phlexible_media_manager.hash_calculator:
        class: Phlexible\Component\Volume\HashCalculator\MessageDigestHashCalculator

    phlexible_media_manager.upload.temp_storage:
        class: Phlexible\Component\MediaManager\Upload\TempStorage
        arguments: [@session, %phlexible_media_manager.temp_dir%]

    phlexible_media_manager.upload.temp_handler:
        class: Phlexible\Component\MediaManager\Upload\TempHandler
        arguments: [@phlexible_media_manager.upload.temp_storage, @phlexible_media_manager.volume_manager]

    phlexible_media_manager.upload.handler:
        class: Phlexible\Component\MediaManager\Upload\UploadHandler
        arguments:
            - @phlexible_media_manager.volume_manager
            - @phlexible_media_manager.upload.temp_storage
            - @phlexible_media_tool.mime.detector

    phlexible_media_manager.util.suggest_field:
        class: Phlexible\Component\MediaManager\Util\SuggestFieldUtil
        arguments:
            - @phlexible_meta_set.meta_set_manager
            - @phlexible_media_manager.folder_meta_data_manager
            - %phlexible_meta_set.suggest.seperator%

    # access control permission providers
    phlexible_media_manager.permission_provider:
        class: Phlexible\Bundle\MediaManagerBundle\AccessControl\MediaManagerPermissionProvider
        tags:
            - {name: phlexible_access_control.permission}

    # event listeners
    phlexible_media_manager.listener.media_site:
        class: Phlexible\Bundle\MediaManagerBundle\EventListener\MediaSiteListener
        arguments:
            - @phlexible_media_type.media_type_manager
            - @phlexible_meta_set.meta_set_manager
            - @phlexible_media_manager.attribute_reader
            - @phlexible_media_manager.delete_file_checker
            - @phlexible_media_manager.delete_folder_checker
            - %phlexible_media_manager.metaset_mapping%
        tags:
            - {name: kernel.event_subscriber}

    phlexible_media_manager.listener.datasource:
        class: Phlexible\Bundle\MediaManagerBundle\EventListener\DatasourceListener
        arguments: [@phlexible_media_manager.util.suggest_field]
        tags:
            - {name: kernel.event_subscriber}

    phlexible_media_manager.listener.get_config:
        class: Phlexible\Bundle\MediaManagerBundle\EventListener\GetConfigListener
        arguments:
            - %phlexible_media_manager.files.num_files%
            - %phlexible_media_manager.files.view%
            - %phlexible_media_manager.upload.disable_flash%
            - %phlexible_media_manager.upload.enable_upload_sort%
            - %phlexible_media_manager.delete_policy%
        tags:
            - {name: kernel.event_listener, event: phlexible_gui.get_config, method: onGetConfig}

    # portlets
    phlexible_media_manager.portlet.latest_files:
        class: Phlexible\Bundle\MediaManagerBundle\Portlet\LatestFilesPortlet
        public: false
        arguments:
            - @phlexible_media_manager.volume_manager
            - @phlexible_media_cache.cache_manager
            - @security.authorization_checker
            - %phlexible_media_manager.portlet.style%
            - %phlexible_media_manager.portlet.num_items%
        tags:
            - {name: phlexible_dashboard.portlet, alias: mediamanager-portlet}

    # role providers
    phlexible_media_manager.role_provider:
        class: Phlexible\Bundle\MediaManagerBundle\RoleProvider\MediaManagerRoleProvider
        public: false
        tags:
            - {name: phlexible_gui.role_provider}

    # searches
    phlexible_media_manager.search.file:
        class: Phlexible\Bundle\MediaManagerBundle\Search\FileSearch
        public: false
        arguments:
            - @phlexible_media_manager.volume_manager
            - @phlexible_user.user_manager
            - @security.authorization_checker
        tags:
            - {name: phlexible_search.provider}

    phlexible_media_manager.search.meta:
        class: Phlexible\Bundle\MediaManagerBundle\Search\MetaSearch
        public: false
        arguments:
            - @phlexible_media_manager.volume_manager
            - @phlexible_media_manager.file_meta_data_manager
            - @phlexible_user.user_manager
            - @security.authorization_checker
        tags:
            - {name: phlexible_search.provider}
