services:
    phlexible_problem.problem_checkers:
        class: Phlexible\Bundle\ProblemBundle\ProblemChecker\ProblemCheckerCollection
        arguments: [[]]

    phlexible_problem.problem_fetcher:
        class: Phlexible\Bundle\ProblemBundle\Problem\ProblemFetcher
        arguments: [@doctrine.orm.entity_manager, @event_dispatcher]

    # event listeners
    phlexible_problem.listener.collect_problems:
        class: Phlexible\Bundle\ProblemBundle\EventListener\CollectProblemsListener
        arguments: [@properties]
        tags:
            - {name: kernel.event_listener, event: phlexible_problem.collect, method: onCollectProblems}

    # portlets
    phlexible_problem.portlet.problems:
        class: Phlexible\Bundle\ProblemBundle\Portlet\ProblemsPortlet
        public: false
        arguments: [@translator, @phlexible_problem.problem_fetcher]
        tags:
            - {name: phlexible_dashboard.portlet}

    # role providers
    phlexible_problem.role_provider:
        class: Phlexible\Bundle\ProblemBundle\RoleProvider\ProblemRoleProvider
        public: false
        tags:
            - {name: phlexible_gui.role_provider}
