services:
    phlexible_elementtype.field.suggest:
        class: Phlexible\Bundle\DataSourceBundle\Field\SuggestField
        public: false
        tags:
            - {name: phlexible_elementtype.field, alias: suggest}
