services:
    phlexible_cache.caches:
        class: Phlexible\Bundle\CacheBundle\Cache\CacheCollection
        arguments: [[]]

    # acl providers
    phlexible_cache.acl_provider:
        class: Phlexible\Bundle\CacheBundle\AclProvider\CacheAclProvider
        public: false
        tags:
            - {name: phlexible_security.acl.provider}

    # asset providers
    phlexible_cache.asset_provider:
        class: Phlexible\Bundle\CacheBundle\AssetProvider\CacheAssetProvider
        public: false
        arguments: [@file_locator]
        tags:
            - {name: phlexible_gui.asset.provider}

    # data collectors
    phlexible_cache.collector:
        class: Phlexible\Bundle\CacheBundle\Collector\CacheCollector
        public: false
        arguments: [@phlexible_cache.caches]
        tags:
            - {name: profiler.collector}

    # portlets
    phlexible_cache.portlet.usage:
        class: Phlexible\Bundle\CacheBundle\Portlet\CacheUsagePortlet
        arguments: [@translator, @phlexible_cache.caches]
        public: false
        tags:
            - {name: phlexible_dashboard.portlet}

    # problem checkers
    phlexible_cache.problem.connection_checker:
        class: Phlexible\Bundle\CacheBundle\ProblemChecker\ConnectionChecker
        public: false
        arguments: [@phlexible_cache.caches]
        tags:
            - {name: phlexible_problem.problem_checker}