services:
    phlexible_form.form_handlers:
        class: Phlexible\Bundle\FormBundle\FormHandler\FormHandlerCollection
        arguments: []

    # asset providers
    phlexible_form.asset_provider:
        class: Phlexible\Bundle\FormBundle\AssetProvider\FormAssetProvider
        public: false
        arguments: [@file_locator]
        tags:
            - {name: phlexible_gui.asset.provider}

    # event listeners
    phlexible_frontend_media.listener.render:
        class: Phlexible\Bundle\FormBundle\EventListener\ElementRendererListener
        arguments: [@phlexible_form.form_handlers]
        tags:
            - {name: kernel.event_subscriber}

    # fields
    phlexible_form.field.form:
        class: Phlexible\Bundle\FormBundle\Field\FormField
        public: false
        tags:
            - {name: phlexible_elementtype.field, alias: form}