services:
    phlexible_element.content_dumper.xml:
        class: Phlexible\Bundle\ElementBundle\ContentElement\Dumper\XmlDumper
        arguments: [%phlexible_element.content.cache_dir%]

    phlexible_element.content_loader.xml:
        class: Phlexible\Bundle\ElementBundle\ContentElement\Loader\XmlLoader
        arguments: [%phlexible_element.content.cache_dir%]
