services:
    phlexible_element.doctrine.element_manager:
        class: Phlexible\Bundle\ElementBundle\Doctrine\ElementManager
        arguments: [@doctrine.orm.entity_manager, @event_dispatcher, @phlexible_message.message_poster]

    phlexible_element.doctrine.element_version_manager:
        class: Phlexible\Bundle\ElementBundle\Doctrine\ElementVersionManager
        arguments: [@doctrine.orm.entity_manager, @event_dispatcher, @phlexible_message.message_poster]

    phlexible_element.doctrine.element_source_manager:
        class: Phlexible\Bundle\ElementBundle\Doctrine\ElementSourceManager
        arguments: [@doctrine.orm.entity_manager, @event_dispatcher, @phlexible_message.message_poster]
