services:
    phlexible_element.field_mapper:
        class: Phlexible\Bundle\ElementBundle\ElementVersion\FieldMapper
        arguments:
            - @phlexible_elementtype.elementtype_service
            - %phlexible_cms.languages.available%
            - []

    # field mappers
    phlexible_element.title_field_mapper:
        class: Phlexible\Bundle\ElementBundle\ElementVersion\TitleFieldMapper
        tags:
            - {name: phlexible_element.field_mapper}

    phlexible_element.custom_date_field_mapper:
        class: Phlexible\Bundle\ElementBundle\ElementVersion\CustomDateFieldMapper
        tags:
            - {name: phlexible_element.field_mapper}

    phlexible_element.forward_field_mapper:
        class: Phlexible\Bundle\ElementBundle\ElementVersion\ForwardFieldMapper
        tags:
            - {name: phlexible_element.field_mapper}
