services:
    elementsTreeTreeHelper:
        class: Phlexible\Bundle\ElementBundle\Tree\TreeHelper
        arguments: [@elementsTreeManager, @elementsVersionManager]

    elementsVersionMetasetManager:
        class: Phlexible\Bundle\ElementBundle\ElementVersion\MetaSetManager
        factory_class: Makeweb_Elements_Element_Version_MetaSet_Manager
        factory_method: getInstance

    elementsTreeSorter:
        class: Makeweb_Elements_Tree_Sorter
        arguments: [@connection_manager, %phlexible_cms.languages.default%]

    elementsContextManager:
        class: Makeweb_Elements_Context_Manager
        arguments: [@connection_manager, %phlexible_element.context.enabled%, %phlexible_element.context.countries%]

    elementsLockService:
        class: Makeweb_Elements_LockService
        arguments: [@locks.repository]

    elementsTreeNodeHash:
        class: Makeweb_Elements_Tree_Node_Hash
        arguments: [@connection_manager]

    elementsNotifications:
        class: Makeweb_Elements_Notifications
        arguments: [@connection_manager]

    elementsFileUsage:
        class: Makeweb_Elements_Element_FileUsage
        arguments: [@connection_manager]

    elementsFolderUsage:
        class: Makeweb_Elements_Element_FolderUsage
        arguments: [@connection_manager]

    elementsLatestElementVersions:
        class: Makeweb_Elements_LatestElementVersions
        arguments: [@phlexible_cache.managed_cache, @connection_manager]
