parameters:
    phlexible_element.overlay.cache_dir: %kernel.cache_dir%/overlays/
    phlexible_element.content.cache_dir: %kernel.cache_dir%/elements/

services:
    phlexible_element.element_service:
        class: Phlexible\Bundle\ElementBundle\ElementService
        arguments:
            - @phlexible_element.element_manager
            - @phlexible_element.element_version_manager
            - @phlexible_element.element_structure_manager
            - @phlexible_elementtype.elementtype_service
            - @phlexible_element.element_history_manager
            - @phlexible_element.field_mapper

    phlexible_element.publish.publisher:
        class: Phlexible\Bundle\ElementBundle\Element\Publish\Publisher
        arguments:
            - @phlexible_element.element_service
            - @phlexible_tree.tree_manager
            - @phlexible_teaser.teaser_manager
            - @security.context

    phlexible_element.publish.selector:
        class: Phlexible\Bundle\ElementBundle\Element\Publish\Selector
        arguments:
            - @phlexible_element.element_service
            - @phlexible_elementtype.elementtype_service
            - @phlexible_tree.tree_manager
            - @phlexible_teaser.teaser_manager
            - @security.context

    phlexible_element.icon_builder:
        class: Phlexible\Bundle\ElementBundle\Icon\IconBuilder
        arguments: [%phlexible_element.overlay.cache_dir%]

    phlexible_element.icon_resolver:
        class: Phlexible\Bundle\ElementBundle\Icon\IconResolver
        arguments: [@router, @phlexible_element.element_service, @phlexible_teaser.teaser_manager]

    phlexible_element.element_meta_set_resolver:
        class: Phlexible\Bundle\ElementBundle\Meta\ElementMetaSetResolver
        arguments: [@phlexible_meta_set.meta_set_manager, @phlexible_element.element_service]

    phlexible_element.element_meta_data_manager:
        class: Phlexible\Bundle\ElementBundle\Meta\ElementMetaDataManager
        arguments: [@doctrine.orm.entity_manager, @phlexible_data_source.data_source_manager, "element_meta"]

    phlexible_element.util.suggest_field:
        class: Phlexible\Bundle\ElementBundle\Util\SuggestFieldUtil
        arguments: [%phlexible_elementtype.field.suggest_seperator%]

    phlexible_element.util.suggest_meta_field:
        class: Phlexible\Bundle\ElementBundle\Util\SuggestMetaFieldUtil
        arguments: [@phlexible_meta_set.meta_set_manager, @phlexible_element.element_meta_data_manager, %phlexible_meta_set.suggest.seperator%]

    phlexible_element.request.data_saver:
        class: Phlexible\Bundle\ElementBundle\Controller\Data\DataSaver
        arguments:
            - @phlexible_element.element_service
            - @phlexible_element.field_mapper
            - @phlexible_elementtype.field.registry
            - @phlexible_tree.tree_manager
            - @phlexible_teaser.teaser_manager
            - @phlexible_element.element_meta_set_resolver
            - @phlexible_element.element_meta_data_manager
            - @event_dispatcher
            - %phlexible_cms.languages.available%

    phlexible_element.element_hasher:
        class: Phlexible\Bundle\ElementBundle\Element\ElementHasher
        arguments: [@phlexible_element.element_service]

    # asset providers
    phlexible_element.asset_provider:
        class: Phlexible\Bundle\ElementBundle\AssetProvider\ElementAssetProvider
        public: false
        arguments: [@file_locator]
        tags:
            - {name: phlexible_gui.asset.provider, priority: 100}

    # event listeners
    phlexible_element.listener.task:
        class: Phlexible\Bundle\ElementBundle\EventListener\TaskListener
        arguments: [@phlexible_task.task_manager, @security.context]
        tags:
            - {name: kernel.event_subscriber}

    phlexible_element.listener.siteroot:
        class: Phlexible\Bundle\ElementBundle\EventListener\SiterootListener
        arguments:
            - @phlexible_element.element_service
            - @phlexible_elementtype.elementtype_service
            - @phlexible_tree.tree_manager
            - @security.context
            - %phlexible_cms.languages.default%]
        tags:
            - {name: kernel.event_listener, event: phlexible_siteroot.create_siteroot, method: onCreateSiteroot}

    phlexible_element.listener.datasource:
        class: Phlexible\Bundle\ElementBundle\EventListener\DatasourceListener
        arguments: [@phlexible_element.util.suggest_field, @phlexible_element.util.suggest_meta_field]
        tags:
            - {name: xkernel.event_subscriber}

    phlexible_element.listener.get_config:
        class: Phlexible\Bundle\ElementBundle\EventListener\GetConfigListener
        arguments: [@service_container]
        tags:
            - {name: kernel.event_listener, event: phlexible_gui.get_config, method: onGetConfig}

    phlexible_element.listener.get_menu:
        class: Phlexible\Bundle\ElementBundle\EventListener\GetMenuListener
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - {name: kernel.event_listener, event: phlexible_gui.get_menu, method: onGetMenu}

    phlexible_element.listener.apply_successor:
        class: Phlexible\Bundle\ElementBundle\EventListener\ApplySuccessorListener
        arguments: [@doctrine.dbal.default_connection]
        tags:
            - {name: kernel.event_listener, event: phlexible_user.apply_successor, method: onApplySuccessor}

    phlexible_element.listener.elementtype_usage:
        class: Phlexible\Bundle\ElementBundle\EventListener\ElementtypeUsageListener
        arguments: [@doctrine.dbal.default_connection, @security.context]
        tags:
            - {name: kernel.event_listener, event: phlexible_elementtype.usage, method: onElementtypeUsage}

    phlexible_element.listener.unlock:
        class: Phlexible\Bundle\ElementBundle\EventListener\UnlockListener
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - {name: kernel.event_listener, event: phlexible_user.before_delete_user, method: onBeforeDeleteUser}
            - {name: kernel.event_listener, event: security.logout, method: onLogout}

    # portlets
    #phlexible_element.portlet.latest:
    #    class: Phlexible\Bundle\ElementBundle\Portlet\LatestElementsPortlet
    #    public: false
    #    arguments: [@translator, @phlexible_element.version.repository, @phlexible_tree.tree_manager, @doctrine.dbal.default_connection, %phlexible_element.portlet.num_items%]
    #    tags:
    #        - {name: phlexible_dashboard.portlet}

    # role providers
    phlexible_element.role_provider:
        class: Phlexible\Bundle\ElementBundle\RoleProvider\ElementRoleProvider
        public: false
        tags:
            - {name: phlexible_gui.role_provider}

    # searches
    phlexible_element.search.eid:
        class: Phlexible\Bundle\ElementBundle\Search\EidSearch
        public: false
        arguments: [@doctrine.dbal.default_connection, %phlexible_cms.languages.default%]
        tags:
            - {name: phlexible_search.handler}

    phlexible_element.search.tid:
        class: Phlexible\Bundle\ElementBundle\Search\TidSearch
        public: false
        arguments: [@doctrine.dbal.default_connection, %phlexible_cms.languages.default%]
        tags:
            - {name: phlexible_search.handler}

    phlexible_element.search.title:
        class: Phlexible\Bundle\ElementBundle\Search\TitleSearch
        public: false
        arguments: [@doctrine.dbal.default_connection, %phlexible_cms.languages.default%]
        tags:
            - {name: phlexible_search.handler}

    phlexible_element.search.unique_id:
        class: Phlexible\Bundle\ElementBundle\Search\UniqueIdSearch
        public: false
        arguments: [@doctrine.dbal.default_connection, %phlexible_cms.languages.default%]
        tags:
            - {name: phlexible_search.handler}