parameters:
    phlexible_element.overlay.cache_dir: %kernel.cache_dir%/overlays/
    phlexible_element.content.cache_dir: %kernel.cache_dir%/elements/

services:
    phlexible_element.element_service:
        class: Phlexible\Bundle\ElementBundle\ElementService
        arguments:
            - @phlexible_element.element_manager
            - @phlexible_element.element_version_manager
            - @phlexible_element.element_source_manager
            - @phlexible_elementtype.viability_manager

    phlexible_element.checker:
        class: Phlexible\Bundle\ElementBundle\Change\Checker
        arguments:
            - @phlexible_elementtype.elementtype_service
            - @phlexible_element.element_service
            - @phlexible_element.element_source_manager
            - @phlexible_elementtype.usage_manager

    phlexible_element.synchronizer:
        class: Phlexible\Bundle\ElementBundle\Change\Synchronizer
        arguments:
            - @phlexible_element.element_manager
            - @phlexible_element.element_version_manager
            - @phlexible_element.element_source_manager
            - @phlexible_elementtype.file.xml_dumper
            - @logger

    phlexible_element.publish.publisher:
        class: Phlexible\Bundle\ElementBundle\Element\Publish\Publisher
        arguments:
            - @phlexible_element.element_service
            - @phlexible_tree.node_manager
            - @phlexible_teaser.teaser_manager
            - @security.authorization_checker

    phlexible_element.publish.selector:
        class: Phlexible\Bundle\ElementBundle\Element\Publish\Selector
        arguments:
            - @phlexible_element.element_service
            - @phlexible_elementtype.elementtype_service
            - @phlexible_tree.node_manager
            - @phlexible_teaser.teaser_manager
            - @security.authorization_checker

    phlexible_element.element_meta_set_resolver:
        class: Phlexible\Bundle\ElementBundle\Meta\ElementMetaSetResolver
        arguments: [@phlexible_meta_set.meta_set_manager, @phlexible_element.element_service]

    phlexible_element.element_meta_data_manager:
        class: Phlexible\Bundle\ElementBundle\Meta\ElementMetaDataManager
        arguments: [@doctrine.orm.entity_manager, @phlexible_data_source.data_source_manager, "element_meta"]

    phlexible_element.util.suggest_field:
        class: Phlexible\Bundle\ElementBundle\Util\SuggestFieldUtil
        arguments: [%phlexible_elementtype.field.suggest_seperator%]

    phlexible_element.util.suggest_meta_field:
        class: Phlexible\Bundle\ElementBundle\Util\SuggestMetaFieldUtil
        arguments: [@phlexible_meta_set.meta_set_manager, @phlexible_element.element_meta_data_manager, %phlexible_meta_set.suggest.seperator%]

    phlexible_element.request.data_saver:
        class: Phlexible\Bundle\ElementBundle\Controller\Data\DataSaver
        arguments:
            - @phlexible_element.element_service
            - @phlexible_elementtype.field.registry
            - @phlexible_tree.tree_manager
            - @phlexible_teaser.teaser_manager
            - @phlexible_element.element_meta_set_resolver
            - @phlexible_element.element_meta_data_manager
            - @event_dispatcher
            - %phlexible_cms.languages.available%

    # event listeners
    phlexible_element.listener.task:
        class: Phlexible\Bundle\ElementBundle\EventListener\TaskListener
        arguments: [@security.token_storage, @?phlexible_task.task_manager]
        tags:
            - {name: kernel.event_subscriber}

    phlexible_element.listener.siteroot:
        class: Phlexible\Bundle\ElementBundle\EventListener\SiterootListener
        arguments:
            - @phlexible_element.element_service
            - @phlexible_elementtype.elementtype_service
            - @phlexible_tree.tree_manager
            - @phlexible_user.user_manager
            - %phlexible_cms.languages.default%]
        tags:
            - {name: kernel.event_listener, event: phlexible_siteroot.create_siteroot, method: onCreateSiteroot}

    phlexible_element.listener.datasource:
        class: Phlexible\Bundle\ElementBundle\EventListener\DatasourceListener
        arguments: [@phlexible_element.util.suggest_field, @phlexible_element.util.suggest_meta_field]
        tags:
            - {name: xkernel.event_subscriber}

    phlexible_element.listener.apply_successor:
        class: Phlexible\Bundle\ElementBundle\EventListener\ApplySuccessorListener
        arguments: [@doctrine.dbal.default_connection]
        tags:
            - {name: kernel.event_listener, event: phlexible_user.apply_successor, method: onApplySuccessor}

    phlexible_element.listener.elementtype_usage:
        class: Phlexible\Bundle\ElementBundle\EventListener\ElementtypeUsageListener
        arguments: [@doctrine.dbal.default_connection, @security.token_storage]
        tags:
            - {name: kernel.event_listener, event: phlexible_elementtype.usage, method: onElementtypeUsage}

    phlexible_element.listener.unlock:
        class: Phlexible\Bundle\ElementBundle\EventListener\UnlockListener
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - {name: kernel.event_listener, event: phlexible_user.before_delete_user, method: onBeforeDeleteUser}
            - {name: kernel.event_listener, event: security.logout, method: onLogout}

    # role providers
    phlexible_element.role_provider:
        class: Phlexible\Bundle\ElementBundle\RoleProvider\ElementRoleProvider
        public: false
        tags:
            - {name: phlexible_gui.role_provider}
