parameters:
    phlexible_element.overlay.cache_dir: %kernel.cache_dir%/overlays/
    phlexible_element.content.cache_dir: %kernel.cache_dir%/elements/

services:
    phlexible_element.element_service:
        class: Phlexible\Bundle\ElementBundle\ElementService
        arguments:
            - @phlexible_element.element_manager
            - @phlexible_element.element_version_manager
            - @phlexible_element.element_structure_manager
            - @phlexible_elementtype.elementtype_service

    phlexible_element.context.manager:
        class: Phlexible\Bundle\ElementBundle\Context\ContextManager

    phlexible_element.field_mapper:
        class: Phlexible\Bundle\ElementBundle\ElementVersion\FieldMapper
        arguments: [@phlexible_element.element_service]

    phlexible_element.content.loader:
        class: Phlexible\Bundle\ElementBundle\ContentElement\ContentElementLoader
        arguments:
            - @event_dispatcher
            - @logger
            - @phlexible_element.content.builder
            - @phlexible_element.content.loader.xml
            - @phlexible_element.content.dumper.xml

    phlexible_element.content.builder:
        class: Phlexible\Bundle\ElementBundle\ContentElement\ContentElementBuilder
        arguments: [@event_dispatcher, @logger, @phlexible_element.element_service]

    phlexible_element.content.dumper.xml:
        class: Phlexible\Bundle\ElementBundle\ContentElement\Dumper\XmlDumper
        arguments: [%phlexible_element.content.cache_dir%]

    phlexible_element.content.loader.xml:
        class: Phlexible\Bundle\ElementBundle\ContentElement\Loader\XmlLoader
        arguments: [%phlexible_element.content.cache_dir%]

    phlexible_element.icon_builder:
        class: Phlexible\Bundle\ElementBundle\Icon\IconBuilder
        arguments: [%phlexible_element.overlay.cache_dir%]

    phlexible_element.icon_resolver:
        class: Phlexible\Bundle\ElementBundle\Icon\IconResolver
        arguments: [@router, @phlexible_element.element_service, @phlexible_tree.state_manager]

    phlexible_element.util.suggest_field:
        class: Phlexible\Bundle\ElementBundle\Util\SuggestFieldUtil
        arguments: [@doctrine.dbal.default_connection, %phlexible_elementtype.field.suggest_seperator%]

    phlexible_element.util.suggest_meta_field:
        class: Phlexible\Bundle\ElementBundle\Util\SuggestMetaFieldUtil
        arguments: [@doctrine.dbal.default_connection, %phlexible_meta_set.suggest.seperator%]

    # acl providers
    phlexible_element.acl_provider:
        class: Phlexible\Bundle\ElementBundle\AclProvider\ElementAclProvider
        public: false
        tags:
            - {name: phlexible_security.acl.provider}

    # asset providers
    phlexible_element.asset_provider:
        class: Phlexible\Bundle\ElementBundle\AssetProvider\ElementAssetProvider
        public: false
        arguments: [@file_locator]
        tags:
            - {name: phlexible_gui.asset.provider, priority: 100}

    # event listeners
    phlexible_element.listener.elementtype:
        class: Phlexible\Bundle\ElementBundle\EventListener\ElementtypeListener
        tags:
            - {name: kernel.event_subscriber}

    phlexible_element.listener.tree_node:
        class: Phlexible\Bundle\ElementBundle\EventListener\TreeNodeListener
        tags:
            - {name: kernel.event_subscriber}

    phlexible_element.listener.siteroot:
        class: Phlexible\Bundle\ElementBundle\EventListener\SiterootListener
        arguments: [@phlexible_element.element_service, @phlexible_tree.tree_manager, @security.context, %phlexible_cms.languages.default%]
        tags:
            - {name: kernel.event_listener, event: phlexible_siteroot.create_siteroot, method: onCreateSiteroot}

    phlexible_element.listener.datasource:
        class: Phlexible\Bundle\ElementBundle\EventListener\DatasourceListener
        arguments: [@phlexible_element.util.suggest_field, @phlexible_element.util.suggest_meta_field]
        tags:
            - {name: xkernel.event_subscriber}

    phlexible_element.listener.get_config:
        class: Phlexible\Bundle\ElementBundle\EventListener\GetConfigListener
        arguments: [@service_container]
        tags:
            - {name: kernel.event_listener, event: phlexible_gui.get_config, method: onGetConfig}

    phlexible_element.listener.get_menu:
        class: Phlexible\Bundle\ElementBundle\EventListener\GetMenuListener
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - {name: kernel.event_listener, event: phlexible_gui.get_menu, method: onGetMenu}

    phlexible_element.listener.apply_successor:
        class: Phlexible\Bundle\ElementBundle\EventListener\ApplySuccessorListener
        arguments: [@doctrine.dbal.default_connection]
        tags:
            - {name: kernel.event_listener, event: phlexible_user.apply_successor, method: onApplySuccessor}

    phlexible_element.listener.elementtype_usage:
        class: Phlexible\Bundle\ElementBundle\EventListener\ElementtypeUsageListener
        arguments: [@doctrine.dbal.default_connection, @security.context]
        tags:
            - {name: kernel.event_listener, event: phlexible_elementtype.usage, method: onElementtypeUsage}

    phlexible_element.listener.unlock:
        class: Phlexible\Bundle\ElementBundle\EventListener\UnlockListener
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - {name: kernel.event_listener, event: phlexible_user.before_delete_user, method: onBeforeDeleteUser}
            - {name: kernel.event_listener, event: security.logout, method: onLogout}

    # portlets
    #phlexible_element.portlet.latest:
    #    class: Phlexible\Bundle\ElementBundle\Portlet\LatestElementsPortlet
    #    public: false
    #    arguments: [@translator, @phlexible_element.version.repository, @phlexible_tree.tree_manager, @doctrine.dbal.default_connection, %phlexible_element.portlet.num_items%]
    #    tags:
    #        - {name: phlexible_dashboard.portlet}

    # searches
    phlexible_element.search.eid:
        class: Phlexible\Bundle\ElementBundle\Search\EidSearch
        public: false
        arguments: [@doctrine.dbal.default_connection, %phlexible_cms.languages.default%]
        tags:
            - {name: phlexible_search.handler}

    phlexible_element.search.tid:
        class: Phlexible\Bundle\ElementBundle\Search\TidSearch
        public: false
        arguments: [@doctrine.dbal.default_connection, %phlexible_cms.languages.default%]
        tags:
            - {name: phlexible_search.handler}

    phlexible_element.search.title:
        class: Phlexible\Bundle\ElementBundle\Search\TitleSearch
        public: false
        arguments: [@doctrine.dbal.default_connection, %phlexible_cms.languages.default%]
        tags:
            - {name: phlexible_search.handler}

    phlexible_element.search.unique_id:
        class: Phlexible\Bundle\ElementBundle\Search\UniqueIdSearch
        public: false
        arguments: [@doctrine.dbal.default_connection, %phlexible_cms.languages.default%]
        tags:
            - {name: phlexible_search.handler}