services:
    phlexible_media_template.applier.audio:
        class: Phlexible\Component\MediaTemplate\Applier\AudioTemplateApplier
        arguments: [@phlexible_media.ffmpeg]

    phlexible_media_template.applier.image:
        class: Phlexible\Component\MediaTemplate\Applier\ImageTemplateApplier
        arguments: [@phlexible_media.imagine]

    phlexible_media_template.applier.video:
        class: Phlexible\Component\MediaTemplate\Applier\VideoTemplateApplier
        arguments: [@phlexible_media.ffmpeg]
