parameters:
    phlexible_media_template.cache_dir: %kernel.cache_dir%/mediatemplates/
    phlexible_media_template.file_dir: %kernel.root_dir%/Resources/mediatemplates/

services:
    phlexible_media_template.file.loader.xml:
        class: Phlexible\Component\MediaTemplate\File\Loader\XmlLoader
        public: false

    phlexible_media_template.file.dumper.xml:
        class: Phlexible\Component\MediaTemplate\File\Dumper\XmlDumper
        public: false

    phlexible_media_template.file.loader:
        class: Phlexible\Component\MediaTemplate\File\PuliTemplateLoader
        public: false
        arguments: [@puli.discovery]
        calls:
            - [addLoader, [@phlexible_media_template.file.loader.xml]]

    phlexible_media_template.file.dumper:
        class: Phlexible\Component\MediaTemplate\File\TemplateDumper
        public: false
        arguments: [@phlexible_media_template.file.dumper.xml, %phlexible_media_template.file_dir%]

    phlexible_media_template.file.template_manager:
        class: Phlexible\Component\MediaTemplate\File\TemplateManager
        public: false
        arguments: [@phlexible_media_template.file.loader, @phlexible_media_template.file.dumper]
