services:
    phlexible_media_template.file.puli_repository:
        class: Phlexible\Component\MediaTemplate\File\PuliTemplateRepository
        public: false
        arguments:
            - @puli.discovery
            - @puli.repository
            - @serializer
            - %phlexible_media_template.dumper.default_type%
            - %phlexible_media_template.dumper.filesystem_dir%
            - %phlexible_media_template.dumper.puli_resource_dir%

    phlexible_media_template.file.template_manager:
        class: Phlexible\Component\MediaTemplate\File\TemplateManager
        public: false
        arguments: [@phlexible_media_template.file.puli_repository]
