parameters:
    phlexible_media_template.cache_dir: %kernel.cache_dir%/mediatemplates/
    phlexible_media_template.file_dir: %kernel.root_dir%/Resources/mediatemplates/

services:
    phlexible_media_template.file.xml_parser:
        class: Phlexible\Component\MediaTemplate\File\Parser\XmlParser
        public: false

    phlexible_media_template.file.xml_dumper:
        class: Phlexible\Component\MediaTemplate\File\Dumper\XmlDumper
        public: false

    phlexible_media_template.file.puli_repository:
        class: Phlexible\Component\MediaTemplate\File\PuliTemplateRepository
        public: false
        arguments:
            - @puli.discovery
            - @puli.repository
            - %phlexible_media_template.dumper.default_type%
            - %phlexible_media_template.dumper.filesystem_dir%
            - %phlexible_media_template.dumper.puli_resource_dir%
        calls:
            - [addParser, ["xml", @phlexible_media_template.file.xml_parser]]
            - [addDumper, ["xml", @phlexible_media_template.file.xml_dumper]]

    phlexible_media_template.file.template_manager:
        class: Phlexible\Component\MediaTemplate\File\TemplateManager
        public: false
        arguments: [@phlexible_media_template.file.puli_repository]
