parameters:
    phlexible_media_template.previewer.temp_dir: %kernel.cache_dir%/mediatemplates/preview/

services:
    phlexible_media_template.previewer.audio:
        class: Phlexible\Component\MediaTemplate\Previewer\AudioPreviewer
        arguments:
            - @phlexible_media_template.applier.audio
            - %phlexible_media_template.previewer.temp_dir%

    phlexible_media_template.previewer.image:
        class: Phlexible\Component\MediaTemplate\Previewer\ImagePreviewer
        arguments:
            - @phlexible_media_template.applier.image
            - %phlexible_media_template.previewer.temp_dir%

    phlexible_media_template.previewer.pdf:
        class: Phlexible\Component\MediaTemplate\Previewer\PdfPreviewer
        arguments:
            - @phlexible_media_template.applier.pdf
            - %phlexible_media_template.previewer.temp_dir%

    phlexible_media_template.previewer.video:
        class: Phlexible\Component\MediaTemplate\Previewer\VideoPreviewer
        arguments:
            - @phlexible_media_template.applier.video
            - %phlexible_media_template.previewer.temp_dir%
