services:
    # asset providers
    phlexible_media_template.asset_provider:
        class: Phlexible\Bundle\MediaTemplateBundle\AssetProvider\MediaTemplatesAssetProvider
        public: false
        tags:
            - {name: phlexible_gui.asset_provider, priority: 600}

    # role providers
    phlexible_media_template.role_provider:
        class: Phlexible\Bundle\MediaTemplateBundle\RoleProvider\MediaTemplateRoleProvider
        public: false
        tags:
            - {name: phlexible_gui.role_provider}
