services:
    phlexible_access_control.permissions:
        class: Phlexible\Bundle\AccessControlBundle\Permission\PermissionCollection
        arguments: [[]]

    phlexible_access_control.permission_resolver:
        class: Phlexible\Bundle\AccessControlBundle\Permission\PermissionResolver
        arguments: [@phlexible_access_control.permissions]

    phlexible_access_control.rights:
        class: Phlexible\Bundle\AccessControlBundle\Rights\Rights
        arguments: [@phlexible_access_control.access_manager, @phlexible_access_control.permissions]

    phlexible_access_control.provider.user:
        class: Phlexible\Bundle\AccessControlBundle\Provider\UserProvider
        arguments: [@phlexible_user.user_manager]

    phlexible_access_control.provider.group:
        class: Phlexible\Bundle\AccessControlBundle\Provider\GroupProvider
        arguments: [@doctrine.orm.entity_manager]

    # voters
    phlexible_access_control.voter.rights:
        class: Phlexible\Bundle\AccessControlBundle\Rights\RightsVoter
        public: false
        arguments: [@phlexible_access_control.access_manager, @phlexible_access_control.permissions]
        tags:
            - {name: security.voter}

    # role providers
    phlexible_access_control.role_provider:
        class: Phlexible\Bundle\AccessControlBundle\RoleProvider\AccessControlRoleProvider
        public: false
        tags:
            - {name: phlexible_gui.role_provider}
