services:
    phlexible_access_control.permission_registry:
        class: Phlexible\Component\AccessControl\Permission\PermissionRegistry
        arguments: [[]]

    phlexible_access_control.permission_resolver:
        class: Phlexible\Component\AccessControl\Permission\PermissionResolver

    phlexible_access_control.provider.user:
        class: Phlexible\Bundle\AccessControlBundle\Provider\UserProvider
        arguments: [@phlexible_user.user_manager]

    phlexible_access_control.provider.group:
        class: Phlexible\Bundle\AccessControlBundle\Provider\GroupProvider
        arguments: [@doctrine.orm.entity_manager]

    # voters
    phlexible_access_control.voter.rights:
        class: Phlexible\Bundle\AccessControlBundle\Voter\AccessControlVoter
        public: false
        arguments: [@phlexible_access_control.access_manager, @phlexible_access_control.permission_registry]
        tags:
            - {name: security.voter}

    # role providers
    phlexible_access_control.role_provider:
        class: Phlexible\Component\AccessControl\RoleProvider\AccessControlRoleProvider
        public: false
        tags:
            - {name: phlexible_gui.role_provider}
