services:
    phlexible_teaser.configurator.teaser:
        class: Phlexible\Bundle\TeaserBundle\Configurator\TeaserConfigurator
        public: false
        arguments: [@event_dispatcher, @logger, @phlexible_teaser.teaser_manager, @phlexible_element.element_service]
        tags:
            - {name: phlexible_cms.configurator, priority: 600}
            - {name: monolog.logger, channel: element_renderer}

    phlexible_teaser.configuration.layoutarea:
        class: Phlexible\Bundle\TeaserBundle\Configurator\LayoutareaConfigurator
        public: false
        arguments:
            - @phlexible_element.element_service
            - @phlexible_element.element_source_manager
            - @phlexible_teaser.teaser_manager
            - @event_dispatcher
            - @logger
        tags:
            - {name: phlexible_cms.configurator, priority: -300}
            - {name: monolog.logger, channel: element_renderer}
