services:
    phlexible_teaser.teaser_hasher:
        class: Phlexible\Bundle\TeaserBundle\Teaser\TeaserHasher
        arguments: [@phlexible_element.element_hasher]

    phlexible_teaser.layoutarea.manager:
        class: Phlexible\Bundle\TeaserBundle\Layoutarea\LayoutareaManager

    phlexible_teaser.rights.provider:
        class: Phlexible\Bundle\TeaserBundle\AccessControl\TeaserRightsProvider
        tags:
            - {name: phlexible_access_control.rights}

    # asset providers
    phlexible_teaser.asset_provider:
        class: Phlexible\Bundle\TeaserBundle\AssetProvider\TeaserAssetProvider
        public: false
        arguments: [@file_locator]
        tags:
            - {name: phlexible_gui.asset.provider, priority: 100}

    # event listeners
    phlexible_teaser.listener.apply_successor:
        class: Phlexible\Bundle\TeaserBundle\EventListener\ApplySuccessorListener
        arguments: [@doctrine.dbal.default_connection]
        tags:
            - {name: kernel.event_listener, event: phlexible_user.apply_successor, method: onApplySuccessor}

    # role providers
    phlexible_teaser.role_provider:
        class: Phlexible\Bundle\TeaserBundle\RoleProvider\TeaserRoleProvider
        public: false
        tags:
            - {name: phlexible_gui.role_provider}
