services:
    phlexible_teaser.area_manager:
        class: Phlexible\Bundle\TeaserBundle\Area\AreaManager
        arguments: [@phlexible_tree.node_manager]

    phlexible_teaser.rights.provider:
        class: Phlexible\Bundle\TeaserBundle\AccessControl\TeaserRightsProvider
        tags:
            - {name: phlexible_access_control.rights}

    # role providers
    phlexible_teaser.role_provider:
        class: Phlexible\Bundle\TeaserBundle\RoleProvider\TeaserRoleProvider
        public: false
        tags:
            - {name: phlexible_gui.role_provider}

    # twig extensions
    phlexible_teaser.twig.teaser_extension:
        class: Phlexible\Bundle\TeaserBundle\Twig\Extension\TeaserExtension
        public: false
        arguments:
            - @phlexible_element.element_service
            - @phlexible_element.element_source_manager
            - @phlexible_teaser.area_manager
            - @request_stack
        tags:
            - {name: twig.extension}
