services:
    # twig extensions
    phlexible_twig_renderer.twig.extension.element:
        class: Phlexible\Bundle\TwigRendererBundle\Twig\Extension\ElementExtension
        public: false
        arguments:
            - @phlexible_element.content_loader
        tags:
            - {name: twig.extension}

    phlexible_twig_renderer.twig.extension.media:
        class: Phlexible\Bundle\TwigRendererBundle\Twig\Extension\MediaExtension
        public: false
        arguments:
            - @router
            - @phlexible_media_site.site_manager
            - @phlexible_media_manager.file_meta_set_resolver
            - @phlexible_media_manager.doctrine.file_meta_data_manager
        tags:
            - {name: twig.extension}

    phlexible_twig_renderer.twig.extension.media_template:
        class: Phlexible\Bundle\TwigRendererBundle\Twig\Extension\MediaTemplateExtension
        public: false
        arguments:
            - @phlexible_media_template.template_manager
        tags:
            - {name: twig.extension}

    phlexible_twig_renderer.twig.extension.misc:
        class: Phlexible\Bundle\TwigRendererBundle\Twig\Extension\MiscExtension
        public: false
        tags:
            - {name: twig.extension}

    phlexible_twig_renderer.twig.extension.tree:
        class: Phlexible\Bundle\TwigRendererBundle\Twig\Extension\TreeExtension
        public: false
        arguments: [@phlexible_tree.content_tree_manager]
        tags:
            - {name: twig.extension}

    phlexible_twig_renderer.twig.extension.url:
        class: Phlexible\Bundle\TwigRendererBundle\Twig\Extension\UrlExtension
        public: false
        arguments: [@router, @phlexible_tree.content_tree_manager.delegating]
        tags:
            - {name: twig.extension}
