services:
    # event listeners
    phlexible_frontend_media.listener.element:
        class: Phlexible\Bundle\FrontendMediaBundle\EventListener\ElementListener
        arguments: [@phlexible_frontend_media.usage_updater]
        tags:
            - {name: kernel.event_subscriber}

    # fields
    phlexible_frontend_media.field.folder:
        class: Phlexible\Bundle\FrontendMediaBundle\Field\FolderField
        public: false
        tags:
            - {name: phlexible_elementtype.field, alias: folder}

    phlexible_frontend_media.field.file:
        class: Phlexible\Bundle\FrontendMediaBundle\Field\FileField
        public: false
        tags:
            - {name: phlexible_elementtype.field, alias: file}
