services:
    phlexible_frontend_media.usage_updater.file:
        class: Phlexible\Bundle\FrontendMediaBundle\Usage\FileUsageUpdater
        arguments:
            - @doctrine.orm.entity_manager
            - @phlexible_tree.tree_manager
            - @phlexible_teaser.teaser_manager
            - @phlexible_media_manager.volume_manager

    phlexible_frontend_media.usage_updater.folder:
        class: Phlexible\Bundle\FrontendMediaBundle\Usage\FolderUsageUpdater
        arguments:
            - @doctrine.orm.entity_manager
            - @phlexible_tree.tree_manager
            - @phlexible_teaser.teaser_manager
            - @phlexible_media_manager.volume_manager

    phlexible_frontend_media.usage_updater:
        class: Phlexible\Bundle\FrontendMediaBundle\Usage\UsageUpdater
        arguments:
            - @phlexible_frontend_media.usage_updater.file
            - @phlexible_frontend_media.usage_updater.folder
