services:
    phlexible_media_tool.image_analyzer:
        class: Brainbits\ImageAnalyzer\ImageAnalyzer
        arguments: [@phlexible_media_tool.image_analyzer.driver]

    phlexible_media_tool.image_analyzer.driver.imagemagick:
        class: Brainbits\ImageAnalyzer\Driver\ImagemagickDriver
        arguments: [@phlexible_media_tool.identify]

    phlexible_media_tool.image_analyzer.driver.imagick:
        class: Brainbits\ImageAnalyzer\Driver\ImagickDriver

    phlexible_media_tool.image_analyzer.driver.gd:
        class: Brainbits\ImageAnalyzer\Driver\GdDriver

