services:
    phlexible_media.exiftool:
        class: PHPExiftool\Reader
        factory: [PHPExiftool\Reader, create]
        arguments: [@logger]
        tags:
            - {name: monolog.logger, channel: media}
