services:
    phlexible_media.ffprobe:
        class: FFMpeg\FFProbe
        factory: [FFMpeg\FFProbe, create]
        arguments: [%phlexible_media.ffmpeg.configuration%, @logger]
        tags:
            - {name: monolog.logger, channel: media}

    phlexible_media.ffmpeg:
        class: FFMpeg\FFMpeg
        factory: [FFMpeg\FFMpeg, create]
        arguments: [%phlexible_media.ffmpeg.configuration%, @logger, @phlexible_media.ffprobe]
        tags:
            - {name: monolog.logger, channel: media}
