services:
    phlexible_media.media_classifier:
        class: Temp\MediaClassifier\MediaClassifier
        arguments:
            - @phlexible_media.media_classifier.collection

    phlexible_media.media_classifier.collection:
        class: Temp\MediaClassifier\Model\MediaTypeCollection
        public: false
        factory_service: phlexible_media.media_classifier.kernel_loader
        factory_method: load
        arguments:
            - %phlexible_media.media_classifier.file%

    phlexible_media.media_classifier.kernel_loader:
        class: Phlexible\Bundle\MediaBundle\MediaClassifier\Loader\KernelLoader
        public: false
        arguments:
            - @phlexible_media.media_classifier.delegating_loader
            - @file_locator

    phlexible_media.media_classifier.delegating_loader:
        class: Temp\MediaClassifier\Loader\DelegatingLoader
        public: false
        arguments:
            - @phlexible_media.media_classifier.loader_resolver

    phlexible_media.media_classifier.loader_resolver:
        class: Temp\MediaClassifier\Loader\LoaderResolver
        public: false
        arguments:
            -
                - @phlexible_media.media_classifier.xml_loader

    phlexible_media.media_classifier.xml_loader:
        class: Temp\MediaClassifier\Loader\XmlLoader
        public: false

