parameters:
    phlexible_media.mime_sniffer.file: file
    phlexible_media.mime_sniffer.magicfile: ~

services:
    phlexible_media.mime_sniffer:
        class: Temp\MimeSniffer\MimeSniffer
        arguments: [@phlexible_media.mime_sniffer.adapter]

    phlexible_media.mime_sniffer.fallback_adapter:
        class: Temp\MimeSniffer\Adapter\FallbackAdapter
        arguments:
            - @phlexible_media.mime_sniffer.file_adapter
            - @phlexible_media.mime_sniffer.extension_adapter

    phlexible_media.mime_sniffer.extension_adapter:
        class: Temp\MimeSniffer\Adapter\ExtensionAdapter

    phlexible_media.mime_sniffer.file_adapter:
        class: Temp\MimeSniffer\Adapter\FileAdapter
        arguments: [%phlexible_media.mime_sniffer.file%]

    phlexible_media.mime_sniffer.fileinfo_adapter:
        class: Temp\MimeSniffer\Adapter\FileinfoAdapter
        arguments: [%phlexible_media.mime_sniffer.magicfile%]

