services:
    phlexible_media.mp4box:
        class: MP4Box\MP4Box
        factory: [MP4Box\MP4Box, create]
        arguments: [%phlexible_media.mp4box.configuration%, @logger]
        tags:
            - {name: monolog.logger, channel: media}
