services:
    phlexible_media.mp4box:
        class: MP4Box\MP4Box
        factory_class: MP4Box\MP4Box
        factory_method: create
        arguments: [%phlexible_media.mp4box.configuration%, @logger]
        tags:
            - {name: monolog.logger, channel: media}
