services:
    phlexible_media.poppler.pdfinfo:
        class: Poppler\Driver\Pdfinfo
        factory: [Poppler\Driver\Pdfinfo, create]
        arguments: [@logger, %phlexible_media.poppler.configuration%]
        tags:
            - {name: monolog.logger, channel: media}

    phlexible_media.poppler.pdftotext:
        class: Poppler\Driver\Pdftotext
        factory: [Poppler\Driver\Pdftotext, create]
        arguments: [@logger, %phlexible_media.poppler.configuration%]
        tags:
            - {name: monolog.logger, channel: media}

    phlexible_media.poppler.pdftohtml:
        class: Poppler\Driver\Pdftohtml
        factory: [Poppler\Driver\Pdftohtml, create]
        arguments: [@logger, %phlexible_media.poppler.configuration%]
        tags:
            - {name: monolog.logger, channel: media}

    phlexible_media.poppler.pdf_file:
        class: Poppler\Processor\PdfFile
        arguments:
            - @phlexible_media.poppler.pdfinfo
            - @phlexible_media.poppler.pdftotext
            - @phlexible_media.poppler.pdftohtml

