services:
    phlexible_media.swftools.driver_container:
        class: SwfTools\Binary\DriverContainer
        arguments:
            - %phlexible_media.swftools.configuration%
            - @logger
        tags:
            - {name: monolog.logger, channel: media}

    phlexible_media.swftools.pdf2swf:
        class: SwfTools\Binary\Pdf2swf
        factory_class: SwfTools\Binary\Pdf2swf
        factory_method: create
        arguments: [%phlexible_media.swftools.configuration%, @logger]
        tags:
            - {name: monolog.logger, channel: media}

    phlexible_media.swftools.swfrender:
        class: SwfTools\Binary\Swfrender
        factory_class: SwfTools\Binary\Swfrender
        factory_method: create
        arguments: [%phlexible_media.swftools.configuration%, @logger]
        tags:
            - {name: monolog.logger, channel: media}

    phlexible_media.swftools.swfextract:
        class: SwfTools\Binary\Swfextract
        factory_class: SwfTools\Binary\Swfextract
        factory_method: create
        arguments: [%phlexible_media.swftools.configuration%, @logger]
        tags:
            - {name: monolog.logger, channel: media}

    phlexible_media.swftools.pdf_file:
        class: SwfTools\Processor\PDFFile
        arguments: [@phlexible_media.swftools.driver_container]

    phlexible_media.swftools.flash_file:
        class: SwfTools\Processor\FlashFile
        arguments: [@phlexible_media.swftools.driver_container]
