services:
    phlexible_media_cache.queue_processor:
        class: Phlexible\Component\MediaCache\Queue\QueueProcessor
        arguments:
            - @phlexible_media_cache.worker.resolver
            - @phlexible_media_manager.volume_manager
            - @phlexible_media_template.template_manager
            - @phlexible_media_type.media_type_manager
            - @properties
            - %app.lock_dir%

    phlexible_media_cache.batch_builder:
        class: Phlexible\Component\MediaCache\Queue\BatchBuilder
        arguments: [@phlexible_media_manager.volume_manager, @phlexible_media_template.template_manager]

    phlexible_media_cache.batch_resolver:
        class: Phlexible\Component\MediaCache\Queue\BatchResolver
        arguments:
            - @phlexible_media_cache.cache_manager
            - @phlexible_media_cache.id_strategy.default
