parameters:
    phlexible_media_cache.temp_dir: %kernel.cache_dir%/mediacache/temp/
    phlexible_media_cache.cache_dir: %kernel.cache_dir%/mediacache/

services:
    phlexible_media_cache.specifier_resolver:
        class: Phlexible\Component\MediaCache\Specifier\SpecifierResolver
        public: false
        arguments:
            -
                - @phlexible_media_cache.audio_specifier
                - @phlexible_media_cache.image_specifier
                - @phlexible_media_cache.video_specifier

    phlexible_media_cache.audio_specifier:
        class: Phlexible\Component\MediaCache\Specifier\AudioSpecifier
        public: false
        tags:
            - {name: phlexible_media_cache.specifier}

    phlexible_media_cache.image_specifier:
        class: Phlexible\Component\MediaCache\Specifier\ImageSpecifier
        public: false
        tags:
            - {name: phlexible_media_cache.specifier}

    phlexible_media_cache.video_specifier:
        class: Phlexible\Component\MediaCache\Specifier\VideoSpecifier
        public: false
        tags:
            - {name: phlexible_media_cache.specifier}

    phlexible_media_cache.worker:
        class: Phlexible\Component\MediaCache\Worker\Worker
        public: false
        arguments:
            - @phlexible_media.transmuter
            - @phlexible_media_cache.specifier_resolver
            - @phlexible_media_cache.storage_manager
            - @phlexible_media_cache.cache_manager
            - @phlexible_media.media_classifier
            - @phlexible_media_cache.id_strategy.default
            - @logger
            - %phlexible_media_cache.temp_dir%
        tags:
            - {name: monolog.logger, channel:media_cache}

    phlexible_media_cache.storage.local:
        class: Phlexible\Component\MediaCache\Storage\LocalStorage
        arguments: [[], @phlexible_media_cache.cache_manager]

    phlexible_media_cache.storage_manager:
        class: Phlexible\Component\MediaCache\Storage\StorageManager
        arguments: [[]]

    phlexible_media_cache.id_strategy.default:
        class: Phlexible\Component\MediaCache\CacheIdStrategy\DefaultCacheIdStrategy

    phlexible_media_cache.image_delegate.worker:
        class: Phlexible\Component\MediaCache\ImageDelegate\DelegateWorker
        arguments:
            - @phlexible_media_template.template_manager
            - @phlexible_media.media_classifier
            - @phlexible_media.transmuter
            - @phlexible_media_type.icon_resolver
            - @file_locator
            - %phlexible_media_cache.cache_dir%

    phlexible_media_cache.image_delegate.service:
        class: Phlexible\Component\MediaCache\ImageDelegate\DelegateService
        arguments: [@phlexible_media_cache.image_delegate.worker]

    # event listeners
    phlexible_media_cache.listener.file:
        class: Phlexible\Bundle\MediaCacheBundle\EventListener\FileListener
        arguments:
            - @phlexible_media_template.template_manager
            - @phlexible_media_cache.queue_processor
            - @phlexible_media_cache.batch_resolver
            - @phlexible_media_cache.cache_manager
            - %phlexible_media_cache.immediately_cache_system_templates%
        tags:
            - {name: kernel.event_subscriber}

    phlexible_media_cache.listener.collect_problems:
        class: Phlexible\Bundle\MediaCacheBundle\EventListener\CollectProblemsListener
        arguments: [@properties]
        tags:
            - {name: kernel.event_listener, event: phlexible_problem.collect, method: onCollectProblems}

    # portlets
    phlexible_media_cache.portlet.cache_status:
        class: Phlexible\Bundle\MediaCacheBundle\Portlet\CacheStatusPortlet
        public: false
        arguments: [@translator, @phlexible_media_cache.cache_manager]
        tags:
            - {name: phlexible_dashboard.portlet}

    # role providers
    phlexible_media_cache.role_provider:
        class: Phlexible\Bundle\MediaCacheBundle\RoleProvider\MediaCacheRoleProvider
        public: false
        tags:
            - {name: phlexible_gui.role_provider}
