services:
    phlexible_tree.configurator.node:
        class: Phlexible\Bundle\TreeBundle\Configurator\NodeConfigurator
        public: false
        arguments: [@event_dispatcher, @logger, @phlexible_element.element_service, @security.authorization_checker]
        tags:
            - {name: phlexible_cms.configurator, priority: 700}
            - {name: monolog.logger, channel: element_renderer}


    phlexible_tree.configurator.navigation:
        class: Phlexible\Bundle\TreeBundle\Configurator\NavigationConfigurator
        public: false
        arguments: [@event_dispatcher, @logger, @phlexible_tree.node_manager]
        tags:
            - {name: phlexible_cms.configurator, priority: -300}
            - {name: monolog.logger, channel: element_renderer}
