services:
    phlexible_tree.doctrine.tree_factory:
        class: Phlexible\Bundle\TreeBundle\Doctrine\TreeFactory
        arguments: [@doctrine.dbal.default_connection, @event_dispatcher, @phlexible_element.element_history_manager]

    phlexible_tree.doctrine.state_manager:
        class: Phlexible\Bundle\TreeBundle\Doctrine\StateManager
        arguments: [@doctrine.dbal.default_connection, @event_dispatcher, @phlexible_element.element_history_manager]
