services:
    phlexible_tree.doctrine.node_manager:
        class: Phlexible\Component\Node\Doctrine\NodeManager
        arguments:
            - @doctrine.orm.entity_manager
            - @phlexible_siteroot.siteroot_manager
            - @event_dispatcher

    phlexible_tree.doctrine.node_state_manager:
        class: Phlexible\Bundle\TreeBundle\Doctrine\NodeStateManager
        arguments:
            - @doctrine.orm.entity_manager
            - @event_dispatcher

    phlexible_tree.doctrine.route_manager:
        class: Phlexible\Bundle\TreeBundle\Doctrine\RouteManager
        arguments:
            - @doctrine.orm.entity_manager
            - @event_dispatcher

    phlexible_tree.doctrine.node_lock_manager:
        class: Phlexible\Bundle\TreeBundle\Doctrine\NodeLockManager
        public: false
        arguments: [@doctrine.orm.entity_manager]

    phlexible_tree.doctrine.node_change_manager:
        class: Phlexible\Bundle\TreeBundle\Doctrine\NodeChangeManager
        public: false
        arguments: [@doctrine.orm.entity_manager]
