services:
    phlexible_tree.doctrine.node_manager:
        class: Phlexible\Bundle\TreeBundle\Doctrine\NodeManager
        arguments:
            - @doctrine.orm.entity_manager
            - @phlexible_siteroot.siteroot_manager
            - @phlexible_tree.node_hasher
            - @event_dispatcher

    phlexible_tree.doctrine.route_manager:
        class: Phlexible\Bundle\TreeBundle\Doctrine\RouteManager
        arguments:
            - @doctrine.orm.entity_manager
            - @event_dispatcher
