services:
    phlexible_tree.mediator.element:
        class: Phlexible\Bundle\TreeBundle\Mediator\ElementTreeMediator
        arguments:
            - @phlexible_element.element_service
            - @phlexible_element.proxy.class_manager
            - @doctrine.orm.entity_manager

    phlexible_tree.mediator:
        class: Phlexible\Bundle\TreeBundle\Mediator\DelegatingTreeMediator
        arguments: [[@phlexible_tree.mediator.element]]
