services:
    phlexible_tree.publish.publisher:
        class: Phlexible\Bundle\TreeBundle\Element\Publish\Publisher
        arguments:
            - @phlexible_element.element_service
            - @phlexible_tree.node_manager
            - @phlexible_teaser.teaser_manager
            - @security.authorization_checker

    phlexible_tree.publish.selector:
        class: Phlexible\Bundle\TreeBundle\Element\Publish\Selector
        arguments:
            - @phlexible_element.element_service
            - @phlexible_elementtype.elementtype_service
            - @phlexible_tree.node_manager
            - @phlexible_teaser.teaser_manager
            - @security.authorization_checker

