services:
    phlexible_tree.tree_manager:
        class: Phlexible\Bundle\TreeBundle\Tree\TreeManager
        arguments:
            - @phlexible_siteroot.siteroot_manager
            - @phlexible_tree.node_manager
            - @phlexible_tree.mediator
            - @event_dispatcher

    phlexible_tree.tree_dumper:
        class: Phlexible\Bundle\TreeBundle\File\Dumper\XmlTreeDumper

    phlexible_tree.routes_dumper:
        class: Phlexible\Bundle\TreeBundle\File\Dumper\XmlRoutesDumper
        arguments: [@phlexible_tree.route_manager]

    phlexible_tree.pattern_resolver:
        class: Phlexible\Bundle\TreeBundle\Pattern\PatternResolver
        arguments: [%phlexible_tree.patterns%, %phlexible_gui.project.title%]

    phlexible_tree.node_serializer:
        class: Phlexible\Bundle\TreeBundle\Node\NodeSerializer
        arguments:
            - @phlexible_element.element_service
            - @phlexible_element.icon_resolver
            - @phlexible_tree.node_manager
            - @phlexible_access_control.permission_registry
            - @security.authorization_checker

    phlexible_tree.node_hasher:
        class: Phlexible\Bundle\TreeBundle\Node\NodeHasher
        arguments: [@phlexible_element.element_hasher]

    phlexible_tree.node_sorter:
        class: Phlexible\Bundle\TreeBundle\Node\NodeSorter
        arguments: [@doctrine.dbal.default_connection, de]

    # access control permission providers
    phlexible_tree.permission_provider:
        class: Phlexible\Bundle\TreeBundle\AccessControl\TreePermissionProvider
        public: false
        tags:
            - {name: phlexible_access_control.permission}

    # event listeners
    phlexible_tree.listener.apply_successor:
        class: Phlexible\Bundle\TreeBundle\EventListener\ApplySuccessorListener
        arguments: [@doctrine.dbal.default_connection]
        tags:
            - {name: kernel.event_listener, event: phlexible_user.apply_successor, method: onApplySuccessor}

    phlexible_tree.listener.exception:
        class: Phlexible\Bundle\TreeBundle\EventListener\ExceptionListener
        arguments:
            - @twig
            - @phlexible_cms.configurator
            - @phlexible_tree.tree_manager
            - @logger
            - %kernel.debug%
        tags:
            - {name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 999}

    phlexible_tree.listener.node:
        class: Phlexible\Bundle\TreeBundle\EventListener\NodeListener
        arguments:
            - @phlexible_tree.doctrine.route_manager
            - @phlexible_siteroot.siteroot_manager
            - @phlexible_tree.node_change_manager
        tags:
            - {name: kernel.event_subscriber}

    phlexible_tree.listener.response:
        class: Phlexible\Bundle\TreeBundle\EventListener\ResponseListener
        arguments: [@router, @phlexible_tree.node_manager]
        tags:
            - {name: kernel.event_listener, event: kernel.response, method: onResponse}

    # twig extensions
    phlexible_tree.twig.tree_extension:
        class: Phlexible\Bundle\TreeBundle\Twig\Extension\TreeExtension
        public: false
        arguments:
            - @phlexible_tree.tree_manager
            - @phlexible_tree.pattern_resolver
            - @request_stack
            - @security.authorization_checker
            - @security.token_storage
        tags:
            - {name: twig.extension}

    phlexible_tree.twig.url_extension:
        class: Phlexible\Bundle\TreeBundle\Twig\Extension\UrlExtension
        public: false
        arguments: [@router, @phlexible_tree.node_manager]
        tags:
            - {name: twig.extension}
