services:
    phlexible_tree.tree_manager:
        class: Phlexible\Bundle\TreeBundle\Tree\TreeManager
        arguments: [@phlexible_siteroot.siteroot_manager, @phlexible_tree.tree_factory]

    phlexible_tree.node_serializer:
        class: Phlexible\Bundle\TreeBundle\Tree\Serializer\NodeSerializer
        arguments:
            - @phlexible_element.element_service
            - @phlexible_element.icon_resolver
            - @phlexible_tree.state_manager
            - @phlexible_access_control.permissions
            - @security.context

    phlexible_tree.content.manager:
        class: Phlexible\Bundle\TreeBundle\ContentTree\ContentTreeManager

    phlexible_tree.router.handler.default:
        class: Phlexible\Bundle\TreeBundle\Router\Handler\DefaultHandler
        arguments:
            - @logger
            - @phlexible_tree.content.manager
            - @phlexible_element.element_service
            - %phlexible_cms.languages.available%
            - %phlexible_cms.languages.default%
        tags:
            - {name: monolog.logger, channel: router}

    phlexible_tree.router:
        class: Phlexible\Bundle\TreeBundle\Router\TreeRouter
        arguments:
            - @router.request_context
            - @phlexible_tree.router.handler.default
            - @phlexible_tree.router.handler.default
            - ""
            - @event_dispatcher
        tags:
            - {name: monolog.logger, channel: router}
            - {name: router, priority: 100}

    # access control permission providers
    phlexible_tree.permission_provider:
        class: Phlexible\Bundle\TreeBundle\AccessControl\TreePermissionProvider
        public: false
        tags:
            - {name: phlexible_access_control.permission}

    # event listeners
    phlexible_tree.listener.apply_successor:
        class: Phlexible\Bundle\TreeBundle\EventListener\ApplySuccessorListener
        arguments: [@doctrine.dbal.default_connection]
        tags:
            - {name: kernel.event_listener, event: phlexible_user.apply_successor, method: onApplySuccessor}
