services:
    phlexible_tree.icon_builder:
        class: Phlexible\Bundle\TreeBundle\Icon\IconBuilder
        arguments: [@file_locator, %phlexible_element.overlay.cache_dir%]

    phlexible_tree.icon_resolver:
        class: Phlexible\Bundle\TreeBundle\Icon\IconResolver
        arguments: [@router, @phlexible_element.element_service, @phlexible_teaser.teaser_manager]

    phlexible_tree.node_context_factory:
        class: Phlexible\Bundle\TreeBundle\Node\NodeContextFactory
        arguments:
            - @phlexible_tree.mediator

    phlexible_tree.tree_factory:
        class: Phlexible\Bundle\TreeBundle\Tree\TreeFactory
        arguments:
            - @phlexible_tree.node_manager
            - @phlexible_tree.node_state_manager
            - @phlexible_tree.node_context_factory
            - @phlexible_tree.node_hasher
            - @event_dispatcher

    phlexible_tree.tree_manager:
        class: Phlexible\Bundle\TreeBundle\Tree\TreeManager
        arguments:
            - @phlexible_siteroot.siteroot_manager
            - @phlexible_tree.node_manager
            - @phlexible_tree.tree_factory
            - @event_dispatcher

    phlexible_tree.tree_dumper:
        class: Phlexible\Bundle\TreeBundle\File\Dumper\XmlTreeDumper

    phlexible_tree.routes_dumper:
        class: Phlexible\Bundle\TreeBundle\File\Dumper\XmlRoutesDumper
        arguments: [@phlexible_tree.route_manager]

    phlexible_tree.pattern_resolver:
        class: Phlexible\Bundle\TreeBundle\Pattern\PatternResolver
        arguments: [%phlexible_tree.patterns%, %phlexible_gui.project.title%]

    phlexible_tree.node_serializer:
        class: Phlexible\Bundle\TreeBundle\Node\NodeSerializer
        arguments:
            - @phlexible_tree.icon_resolver
            - @phlexible_tree.node_manager
            - @phlexible_access_control.permission_registry
            - @security.authorization_checker

    phlexible_tree.node_hasher:
        class: Phlexible\Bundle\TreeBundle\Node\NodeHasher
        arguments: ["sha1"]

    phlexible_tree.node_sorter:
        class: Phlexible\Bundle\TreeBundle\Node\NodeSorter
        arguments: [@doctrine.dbal.default_connection, de]

    # access control permission providers
    phlexible_tree.permission_provider:
        class: Phlexible\Bundle\TreeBundle\AccessControl\TreePermissionProvider
        public: false
        tags:
            - {name: phlexible_access_control.permission}

    # event listeners
    phlexible_tree.listener.apply_successor:
        class: Phlexible\Bundle\TreeBundle\EventListener\ApplySuccessorListener
        arguments: [@doctrine.dbal.default_connection]
        tags:
            - {name: kernel.event_listener, event: phlexible_user.apply_successor, method: onApplySuccessor}

    phlexible_tree.listener.exception:
        class: Phlexible\Bundle\TreeBundle\EventListener\ExceptionListener
        arguments:
            - @twig
            - @phlexible_cms.configurator
            - @phlexible_tree.tree_manager
            - @logger
            - %kernel.debug%
        tags:
            - {name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 999}

    phlexible_tree.listener.get_config:
        class: Phlexible\Bundle\TreeBundle\EventListener\GetConfigListener
        arguments:
            - @phlexible_siteroot.siteroot_manager
            - @phlexible_tree.tree_manager
            - @security.authorization_checker
            - %phlexible_tree.publish.comment_required%
            - %phlexible_tree.publish.confirm_required%
            - %phlexible_tree.create.use_multilanguage%
            - %phlexible_tree.create.restricted%
            - %phlexible_cms.languages.available%
        tags:
            - {name: kernel.event_listener, event: phlexible_gui.get_config, method: onGetConfig}

    phlexible_tree.listener.get_menu:
        class: Phlexible\Bundle\TreeBundle\EventListener\GetMenuListener
        arguments:
            - @phlexible_siteroot.siteroot_manager
            - @phlexible_tree.tree_manager
            - @security.authorization_checker
        tags:
            - {name: kernel.event_listener, event: phlexible_gui.get_menu, method: onGetMenu}

    phlexible_tree.listener.node:
        class: Phlexible\Bundle\TreeBundle\EventListener\NodeListener
        arguments:
            - @phlexible_tree.doctrine.route_manager
            - @phlexible_siteroot.siteroot_manager
            - @phlexible_tree.node_change_manager
        tags:
            - {name: kernel.event_subscriber}

    phlexible_tree.listener.response:
        class: Phlexible\Bundle\TreeBundle\EventListener\ResponseListener
        arguments: [@router, @phlexible_tree.node_manager]
        tags:
            - {name: kernel.event_listener, event: kernel.response, method: onResponse}

    # portlets
    phlexible_tree.portlet.latest_node_changes:
        class: Phlexible\Bundle\TreeBundle\Portlet\LatestNodeChangesPortlet
        public: false
        arguments:
            - @translator
            - @phlexible_tree.tree_manager
            - @phlexible_tree.node_manager
            - @phlexible_tree.icon_resolver
            - %phlexible_tree.portlet.num_items%
        tags:
            - {name: phlexible_dashboard.portlet}

    # searches
    phlexible_tree.search.node_id:
        class: Phlexible\Bundle\TreeBundle\Search\NodeIdSearch
        public: false
        arguments:
            - @phlexible_tree.tree_manager
            - @phlexible_siteroot.siteroot_manager
            - @phlexible_tree.icon_resolver
            - @security.authorization_checker
            - %phlexible_cms.languages.default%
        tags:
            - {name: phlexible_search.provider}

    phlexible_tree.search.node_title:
        class: Phlexible\Bundle\TreeBundle\Search\NodeTitleSearch
        public: false
        arguments:
            - @doctrine.orm.entity_manager
            - @phlexible_tree.tree_manager
            - @phlexible_siteroot.siteroot_manager
            - @phlexible_tree.icon_resolver
            - @security.authorization_checker
        tags:
            - {name: phlexible_search.provider}

    # twig extensions
    phlexible_tree.twig.tree_extension:
        class: Phlexible\Bundle\TreeBundle\Twig\Extension\TreeExtension
        public: false
        arguments:
            - @phlexible_tree.tree_manager
            - @phlexible_tree.pattern_resolver
            - @request_stack
            - @security.authorization_checker
            - @security.token_storage
        tags:
            - {name: twig.extension}

    phlexible_tree.twig.url_extension:
        class: Phlexible\Bundle\TreeBundle\Twig\Extension\UrlExtension
        public: false
        arguments: [@router, @phlexible_tree.node_manager]
        tags:
            - {name: twig.extension}
