services:
    phlexible_media_extractor.extractor.audio.raw:
        class: Phlexible\Bundle\MediaExtractorBundle\AudioExtractor\RawAudioExtractor
        public: false
        tags:
            - {name: phlexible_media_asset.audio_extractor}
