services:
    phlexible_media_extractor.extractor.audio.raw:
        class: Phlexible\Component\MediaExtractor\AudioExtractor\RawAudioExtractor
        public: false
        tags:
            - {name: phlexible_media_extractor.extractor}
