services:
    phlexible_media_extractor.extractor.content.pdftotext:
        class: Phlexible\Bundle\MediaExtractorBundle\ContentExtractor\PdfToTextExtractor
        public: false
        arguments: [@phlexible_media_tool.poppler.pdf_file]

    phlexible_media_extractor.extractor.content.rawtext:
        class: Phlexible\Bundle\MediaExtractorBundle\ContentExtractor\RawTextExtractor
        public: false

    phlexible_media_extractor.extractor.content.zendlucenedocx:
        class: Phlexible\Bundle\MediaExtractorBundle\ContentExtractor\ZendLuceneDocxExtractor
        public: false

    phlexible_media_extractor.extractor.content.zendlucenepptx:
        class: Phlexible\Bundle\MediaExtractorBundle\ContentExtractor\ZendLucenePptxExtractor
        public: false

    phlexible_media_extractor.extractor.content.zendlucenexlsx:
        class: Phlexible\Bundle\MediaExtractorBundle\ContentExtractor\ZendLuceneXlsxExtractor
        public: false

    phlexible_media_extractor.extractor.content.resolver:
        class: Phlexible\Bundle\MediaExtractorBundle\Extractor\ExtractorResolver
        public: false
        arguments:
            -
                - @phlexible_media_extractor.extractor.content.pdftotext
                - @phlexible_media_extractor.extractor.content.rawtext
                - @phlexible_media_extractor.extractor.content.zendlucenedocx
                - @phlexible_media_extractor.extractor.content.zendlucenepptx
                - @phlexible_media_extractor.extractor.content.zendlucenexlsx

    phlexible_media_extractor.extractor.content:
        class: Phlexible\Bundle\MediaExtractorBundle\Extractor\DelegatingExtractor
        arguments: [@phlexible_media_extractor.extractor.content.resolver]
        tags:
            - {name: phlexible_media_extractor.extractor}
