services:
    phlexible_media_extractor.extractor.flash.raw:
        class: Phlexible\Component\MediaExtractor\FlashExtractor\RawFlashExtractor
        public: false
        tags:
            - {name: phlexible_media_extractor.extractor}
