services:
    phlexible_media_extractor.extractor.image.video_converter:
        class: Phlexible\Component\MediaExtractor\ImageExtractor\VideoConverterImageExtractor
        public: false
        arguments: [@phlexible_media_tool.ffmpeg, %phlexible_media_extractor.asset_temp_dir%]
        tags:
            - {name: phlexible_media_extractor.extractor}

    phlexible_media_extractor.extractor.image.getid3:
        class: Phlexible\Component\MediaExtractor\ImageExtractor\GetId3ImageExtractor
        public: false
        arguments: [%phlexible_media_extractor.asset_temp_dir%, @logger]
        tags:
            - {name: phlexible_media_extractor.extractor}
            - {name: monolog.logger, channel: media_asset}

    phlexible_media_extractor.extractor.image.raw:
        class: Phlexible\Component\MediaExtractor\ImageExtractor\RawImageExtractor
        public: false
        tags:
            - {name: phlexible_media_extractor.extractor}
