parameters:
    phlexible_media_extractor.asset_temp_dir: %kernel.cache_dir%/extractor

services:
    phlexible_media_extractor.transmutor:
        class: Phlexible\Bundle\MediaExtractorBundle\Transmutor
        arguments:
            - @phlexible_media_type.media_type_manager
            - @phlexible_media_extractor.extractor

    phlexible_media_extractor.extractor.resolver:
        class: Phlexible\Bundle\MediaExtractorBundle\Extractor\ExtractorResolver
        public: false
        arguments: [[]]

    phlexible_media_extractor.extractor:
        class: Phlexible\Bundle\MediaExtractorBundle\Extractor\DelegatingExtractor
        arguments:
            - @phlexible_media_extractor.extractor.resolver
