services:
    phlexible_media_extractor.extractor.video.raw:
        class: Phlexible\Bundle\MediaExtractorBundle\VideoExtractor\RawVideoExtractor
        public: false
        tags:
            - {name: phlexible_media_asset.video_extractor}
