services:
    # acl providers
    phlexible_lock.acl_provider:
        class: Phlexible\Bundle\LockBundle\AclProvider\LockAclProvider
        public: false
        tags:
            - {name: phlexible_security.acl.provider}

    # asset providers
    phlexible_lock.asset_provider:
        class: Phlexible\Bundle\LockBundle\AssetProvider\LockAssetProvider
        public: false
        arguments: [@file_locator]
        tags:
            - {name: phlexible_gui.asset.provider}

    # event listeners
    phlexible_lock.listener.unlock:
        class: Phlexible\Bundle\LockBundle\EventListener\UnlockListener
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - {name: kernel.event_listener, event: phlexible_user.before_delete_user, method: onBeforeDeleteUser}
            - {name: kernel.event_listener, event: security.logout, method: onLogout}

    # portlets
    phlexible_lock.portlet.list:
        class: Phlexible\Bundle\LockBundle\Portlet\MyLocksPortlet
        public: false
        arguments: [@translator, @phlexible_lock.lock_manager, @security.context]
        tags:
            - {name: phlexible_dashboard.portlet}
