parameters:
    phlexible_documenttype.compiler.cache_dir: %kernel.cache_dir%/documenttypes/

services:
    phlexible_documenttype.icon_resolver:
        class: Phlexible\Bundle\DocumenttypeBundle\Model\IconResolver
        arguments: [@file_locator]

    phlexible_documenttype.compiler.php:
        class: Phlexible\Bundle\DocumenttypeBundle\Compiler\PhpCompiler
        public: false

    phlexible_documenttype.compiler.script:
        class: Phlexible\Bundle\DocumenttypeBundle\Compiler\ScriptCompiler
        public: false

    phlexible_documenttype.compiler.css:
        class: Phlexible\Bundle\DocumenttypeBundle\Compiler\CssCompiler
        public: false

    # asset providers
    phlexible_documenttype.asset_provider:
        class: Phlexible\Bundle\DocumenttypeBundle\AssetProvider\DocumenttypesAssetProvider
        public: false
        arguments:
            - @phlexible_documenttype.documenttype_manager
            - @phlexible_documenttype.compiler.script
            - @phlexible_documenttype.compiler.css
            - %phlexible_documenttype.compiler.cache_dir%
        tags:
            - {name: phlexible_gui.asset_provider, priority: 600}

    # role provider
    phlexible_documenttype.role_provider:
        class: Phlexible\Bundle\DocumenttypeBundle\RoleProvider\DocumenttypeRoleProvider
        public: false
        tags:
            - {name: phlexible_gui.role_provider}
