parameters:
    phlexible_documenttype.compiler.cache_dir: %kernel.cache_dir%/documenttypes/

services:
    phlexible_documenttype.compiler.php:
        class: Phlexible\Bundle\DocumenttypeBundle\Compiler\PhpCompiler
        public: false
        arguments: [%phlexible_documenttype.compiler.cache_dir%]

    phlexible_documenttype.compiler.script:
        class: Phlexible\Bundle\DocumenttypeBundle\Compiler\ScriptCompiler
        public: false
        arguments: [%phlexible_documenttype.compiler.cache_dir%]

    phlexible_documenttype.compiler.css:
        class: Phlexible\Bundle\DocumenttypeBundle\Compiler\CssCompiler
        public: false
        arguments: [%phlexible_documenttype.compiler.cache_dir%]

    # acl provider
    phlexible_documenttype.acl_provider:
        class: Phlexible\Bundle\DocumenttypeBundle\AclProvider\DocumenttypeAclProvider
        public: false
        tags:
            - {name: phlexible_security.acl.provider}

    # asset providers
    phlexible_documenttype.asset_provider:
        class: Phlexible\Bundle\DocumenttypeBundle\AssetProvider\DocumenttypesAssetProvider
        public: false
        arguments:
            - @phlexible_documenttype.documenttype_manager
            - @phlexible_documenttype.compiler.script
            - @phlexible_documenttype.compiler.css
            - @file_locator
            - %phlexible_documenttype.compiler.cache_dir%
        tags:
            - {name: phlexible_gui.asset.provider, priority: 600}
