services:
    phlexible_siteroot.puli_repository:
        class: Phlexible\Component\Site\File\PuliSiteRepository
        public: false
        arguments:
            - @puli.discovery
            - @puli.repository
            - @serializer
            - "xml"
            - "%kernel.root_dir%/Resources/sites"
            - "/tipfinder/sites"

    phlexible_siteroot.siteroot_manager.default:
        class: Phlexible\Component\Site\File\SiteManager
        public: false
        arguments:
            - @phlexible_siteroot.puli_repository
            - @validator
            - @event_dispatcher
        public: false
