services:
    phlexible_siteroot.siteroot_saver:
        class: Phlexible\Bundle\SiterootBundle\Controller\Siteroot\SiterootSaver
        arguments: [@phlexible_siteroot.siteroot_manager]

    phlexible_siteroot.siteroot_request_matcher:
        class: Phlexible\Component\Site\Site\SiteRequestMatcher
        arguments: [@phlexible_siteroot.siteroot_manager, %phlexible_siteroot.mappings%]

    phlexible_siteroot.siteroot_hostname_mapper:
        class: Phlexible\Component\Site\Site\SiteHostnameMapper
        arguments: [%phlexible_siteroot.mappings%]

    phlexible_siteroot.siteroot_hostname_generator:
        class: Phlexible\Component\Site\Site\SiteHostnameGenerator
        arguments: [@phlexible_siteroot.siteroot_hostname_mapper]

    phlexible_siteroot.siteroots_accessor:
        class: Phlexible\Component\Site\Site\SitesAccessor
        arguments: [@phlexible_siteroot.siteroot_manager]

    # event listeners
    phlexible_siteroot.listener.apply_successor:
        class: Phlexible\Bundle\SiterootBundle\EventListener\ApplySuccessorListener
        arguments: [@phlexible_siteroot.siteroot_manager]
        tags:
            - {name: kernel.event_listener, event: phlexible_user.apply_successor, method: onApplySuccessor}

    # problem checkers
    phlexible_siteroot.problem.siterootcheck:
        class: Phlexible\Bundle\SiterootBundle\ProblemChecker\SiterootProblemChecker
        public: false
        arguments: [@phlexible_siteroot.siteroot_manager]
        tags:
            - {name: phlexible_problem.problem_checker}

    # role providers
    phlexible_siteroot.role_provider:
        class: Phlexible\Bundle\SiterootBundle\RoleProvider\SiterootRoleProvider
        public: false
        tags:
            - {name: phlexible_gui.role_provider}

    # twig extensions
    phlexible_siteroot.twig.siteroot_extension:
        class: Phlexible\Bundle\SiterootBundle\Twig\Extension\SiterootExtension
        public: false
        arguments:
            - @phlexible_siteroot.siteroot_manager
            - @phlexible_siteroot.siteroot_request_matcher
            - @phlexible_siteroot.siteroots_accessor
            - @request_stack
        tags:
            - {name: twig.extension}
