services:
    phlexible_siteroot.siteroot_saver:
        class: Phlexible\Bundle\SiterootBundle\Controller\Siteroot\SiterootSaver
        arguments: [@phlexible_siteroot.siteroot_manager]

    phlexible_siteroot.pattern_resolver:
        class: Phlexible\Bundle\SiterootBundle\Siteroot\PatternResolver
        arguments: [@translator, %phlexible_gui.project.title%]

    # event listeners
    phlexible_siteroot.listener.apply_successor:
        class: Phlexible\Bundle\SiterootBundle\EventListener\ApplySuccessorListener
        arguments: [@phlexible_siteroot.siteroot_manager]
        tags:
            - {name: kernel.event_listener, event: phlexible_user.apply_successor, method: onApplySuccessor}

    # problem checkers
    phlexible_siteroot.problem.siterootcheck:
        class: Phlexible\Bundle\SiterootBundle\ProblemChecker\SiterootProblemChecker
        public: false
        arguments: [@phlexible_siteroot.siteroot_manager]
        tags:
            - {name: phlexible_problem.problem_checker}

    # role providers
    phlexible_siteroot.role_provider:
        class: Phlexible\Bundle\SiterootBundle\RoleProvider\SiterootRoleProvider
        public: false
        tags:
            - {name: phlexible_gui.role_provider}

    # twig extensions
    phlexible_siteroot.twig.siteroot_extension:
        class: Phlexible\Bundle\SiterootBundle\Twig\Extension\SiterootExtension
        public: false
        arguments: [@request_stack, @phlexible_siteroot.siteroot_manager, @phlexible_siteroot.pattern_resolver]
        tags:
            - {name: twig.extension}
