services:
    phlexible_message.message_manager.default:
        class: Phlexible\Bundle\MessageBundle\Elastica\MessageManager
        public: false
        arguments:
            - @phlexible_elastica.default_client
            - %phlexible_message.elastica_index_name%
            - %phlexible_message.elastica_type_name%
