parameters:
    phlexible_message.mailer.digest.from:      %phlexible_gui.mail.from_email%
    phlexible_message.mailer.digest.template:  PhlexibleMessageBundle:Digest:email.txt.twig
    phlexible_message.mailer.message.from:     %phlexible_gui.mail.from_email%
    phlexible_message.mailer.message.template: PhlexibleMessageBundle:Message:email.txt.twig

services:
    phlexible_message.message_handler:
        class: Phlexible\Bundle\MessageBundle\Handler\ChainHandler
        arguments: [[]]

    phlexible_message.message_poster:
        class: Phlexible\Bundle\MessageBundle\Message\MessagePoster
        arguments: [@event_dispatcher]

    phlexible_message.digest_assembler:
        class: Phlexible\Bundle\MessageBundle\Digest\DigestAssembler
        arguments:
            - @phlexible_message.subscription_manager
            - @phlexible_message.filter_manager
            - @phlexible_message.message_manager
            - @phlexible_user.user_manager

    phlexible_message.digester:
        class: Phlexible\Bundle\MessageBundle\Digest\Digester
        arguments:
            - @phlexible_message.digest_assembler
            - @phlexible_message.message_poster
            - @phlexible_message.digest_mailer

    phlexible_message.digest_mailer:
        class: Phlexible\Bundle\MessageBundle\Mailer\DigestMailer
        arguments:
            - @twig
            - @mailer
            - @logger
            -
                digest: {from: %phlexible_message.mailer.digest.from%, template: %phlexible_message.mailer.digest.template%}
                from: {from: %phlexible_message.mailer.message.from%, template: %phlexible_message.mailer.message.template%}
        tags:
            - {name: monolog.logger, channel: mailer}

    phlexible_message.handler.debug:
        class: Phlexible\Bundle\MessageBundle\Handler\DebugHandler
        public: false

    phlexible_message.handler.log:
        class: Phlexible\Bundle\MessageBundle\Handler\LogHandler
        public: false
        arguments: [@logger]

    phlexible_message.handler.message_manager:
        class: Phlexible\Bundle\MessageBundle\Handler\BufferHandler
        public: false
        arguments: [@phlexible_message.handler.message_manager.real]

    phlexible_message.handler.message_manager.real:
        class: Phlexible\Bundle\MessageBundle\Handler\MessageManagerHandler
        public: false
        arguments: [@phlexible_message.message_manager]

    # data collectors
    phlexible_message.data_collector.messages:
        class: Phlexible\Bundle\MessageBundle\DataCollector\MessagesDataCollector
        public: false
        arguments: [@phlexible_message.handler.debug]
        tags:
            - {name: data_collector, template: @PhlexibleMessage/Collector/messages.html.twig, id: messages, priority: 0}

    # event listeners
    phlexible_message.listener.get_config:
        class: Phlexible\Bundle\MessageBundle\EventListener\GetConfigListener
        arguments:
            - @phlexible_message.message_manager
        tags:
            - {name: kernel.event_listener, event: phlexible_gui.get_config, method: onGetConfig}

    phlexible_message.listener.message:
        class: Phlexible\Bundle\MessageBundle\EventListener\MessageListener
        arguments: [@phlexible_message.message_handler]
        tags:
            - {name: kernel.event_subscriber}

    # portlets
    phlexible_message.portlet.messages:
        class: Phlexible\Bundle\MessageBundle\Portlet\MessagesPortlet
        public: false
        arguments:
            - @phlexible_message.subscription_manager
            - @phlexible_message.message_manager
            - @security.token_storage
        tags:
            - {name: phlexible_dashboard.portlet, alias: messages-portlet}

    # role providers
    phlexible_message.role_provider:
        class: Phlexible\Bundle\MessageBundle\RoleProvider\MessageRoleProvider
        public: false
        tags:
            - {name: phlexible_gui.role_provider}

    # serialization handler
    phlexible_message.serialization_handler:
        class: Phlexible\Bundle\MessageBundle\Serialization\ExpressionHandler
        tags:
            - {name: jms_serializer.subscribing_handler}
