parameters:
    phlexible_contentchannel.file_dir: %kernel.root_dir%/Resources/contentchannels/

services:
    # role providers
    phlexible_contentchannel.role_provider:
        class: Phlexible\Bundle\ContentchannelBundle\RoleProvider\ContentchannelRoleProvider
        public: false
        public: false
        tags:
            - {name: phlexible_gui.role_provider}
