services:
    api_key_user_provider:
        class: Phlexible\Bundle\GuiBundle\Security\ApiKeyUserProvider
        arguments: [@phlexible_user.user_manager]

    apikey_authenticator:
        class:     Phlexible\Bundle\GuiBundle\Security\ApiKeyAuthenticator
        arguments: [@api_key_user_provider]