main:
    xtype: Phlexible.gui.menuhandle.MainGroup

menus:
    xtype: Phlexible.gui.menuhandle.MenusGroup

config:
    parent: menus
    xtype: Phlexible.gui.menuhandle.ConfigurationMenu

admin:
    parent: menus
    xtype: Phlexible.gui.menuhandle.AdministrationMenu

debug:
    parent: menus
    xtype: Phlexible.gui.menuhandle.DebugMenu

fill:
    xtype: Phlexible.gui.menuhandle.Fill

account:
    xtype: Phlexible.gui.menuhandle.AccountGroup

tray:
    xtype: Phlexible.gui.menuhandle.TrayGroup

help:
    parent: account
    xtype: Phlexible.gui.menuhandle.HelpHandle

phpinfo:
    parent: debug
    xtype: Phlexible.gui.menuhandle.PhpInfoHandle
    roles: [ROLE_DEBUG]

#properties:
#    parent: debug
#    xtype: Phlexible.gui.menuhandle.PropertiesHandle
#    roles: [ROLE_DEBUG]

components:
    parent: admin
    xtype: Phlexible.gui.menuhandle.BundlesHandle
    roles: [ROLE_BUNDLES]
