parameters:
    app.lock_dir: %kernel.cache_dir%/locks/
    app.web_dir:  %kernel.root_dir%/../web/

services:
    pattern_locator:
        class: Phlexible\Bundle\GuiBundle\Locator\PatternResourceLocator
        arguments: [@kernel, "%kernel.root_dir%/Resources"]

    properties:
        class: Phlexible\Bundle\GuiBundle\Properties\Properties
        arguments: [@doctrine.orm.entity_manager]

    phlexible_gui.view.index:
        class: Phlexible\Bundle\GuiBundle\View\IndexView
        arguments: [@event_dispatcher]

    phlexible_gui.builder.config:
        class: Phlexible\Bundle\GuiBundle\Config\ConfigBuilder
        arguments:
            - @event_dispatcher
            - @security.context
            - %phlexible_gui.languages.available%
            - %phlexible_gui.languages.default%

    phlexible_gui.menu.loader:
        class: Phlexible\Bundle\GuiBundle\Menu\MenuLoader
        arguments: [@puli.discovery, @event_dispatcher]

    phlexible_gui.catalog_accessor:
        class: Phlexible\Bundle\GuiBundle\Translator\CatalogAccessor
        arguments: [@translator]


    phlexible_gui.security.role_hierarchy_factory:
        class: Phlexible\Bundle\GuiBundle\Security\RoleHierarchyFactory
        arguments: [%security.role_hierarchy.roles%]

    security.role_hierarchy:
        class: Symfony\Component\Security\Core\Role\RoleHierarchy
        factory_service: phlexible_gui.security.role_hierarchy_factory
        factory_method: factory
        public: false

    phlexible_gui.security.access.role_hierarchy_voter:
        class: Symfony\Component\Security\Core\Authorization\Voter\RoleHierarchyVoter
        public: false
        arguments: [@security.role_hierarchy]
        tags:
            - {name: security.voter, priority: 245}

    # compressors
    phlexible_gui.compressor.javascript.simple:
        class: Phlexible\Bundle\GuiBundle\Compressor\SimpleJavascriptCompressor
        public: false
        tags:
            - {name: phlexible_gui.compressor.javascript, priority: -100}

    phlexible_gui.compressor.css.simple:
        class: Phlexible\Bundle\GuiBundle\Compressor\SimpleCssCompressor
        public: false
        tags:
            - {name: phlexible_gui.compressor.css, priority: -100}

    # portlets
    phlexible_gui.portlet.load:
        class: Phlexible\Bundle\GuiBundle\Portlet\LoadPortlet
        public: false
        arguments: [@translator]
        tags:
            - {name: phlexible_dashboard.portlet}

    # role providers
    phlexible_gui.role_provider:
        class: Phlexible\Bundle\GuiBundle\RoleProvider\GuiRoleProvider
        public: false
        tags:
            - {name: phlexible_gui.role_provider}

