services:
    # twig extensions
    phlexible_gui.twig.extension.gui:
        class: Phlexible\Bundle\GuiBundle\Twig\Extension\GuiExtension
        arguments:
            - %phlexible_gui.project.title%
            - %phlexible_gui.project.version%
            - %phlexible_gui.project.url%
        tags:
            - {name: twig.extension}
