
services:
    wsse.security.authentication.provider:
        class: Phlexible\Bundle\GuiBundle\Security\Authentication\Provider\WsseProvider
        arguments: ["", "%kernel.cache_dir%/security/nonces"]

    wsse.security.authentication.listener:
        class: Phlexible\Bundle\GuiBundle\Security\Firewall\WsseListener
        arguments: ["@security.token_storage", "@security.authentication.manager", "@logger"]