services:
    phlexible_meta_set.file.xml_parser:
        class: Phlexible\Component\MetaSet\File\Parser\XmlParser
        public: false

    phlexible_meta_set.file.xml_dumper:
        class: Phlexible\Component\MetaSet\File\Dumper\XmlDumper
        public: false

    phlexible_meta_set.file.repository:
        class: Phlexible\Component\MetaSet\File\PuliMetaSetRepository
        public: false
        arguments:
            - @puli.discovery
            - @puli.repository
            - %phlexible_meta_set.dumper.default_type%
            - %phlexible_meta_set.dumper.filesystem_dir%
            - %phlexible_meta_set.dumper.puli_resource_dir%
        calls:
            - [addParser, ["xml", @phlexible_meta_set.file.xml_parser]]
            - [addDumper, ["xml", @phlexible_meta_set.file.xml_dumper]]

    phlexible_meta_set.file.meta_set_manager:
        class: Phlexible\Component\MetaSet\File\MetaSetManager
        arguments: [@phlexible_meta_set.file.repository]
