parameters:
    phlexible_meta_set.file_dir: %kernel.root_dir%/meta_sets
    phlexible_meta_set.languages.default: en
    phlexible_meta_set.languages.available: en,de
    phlexible_meta_set.suggest.seperator: ,

services:
    phlexible_meta_set.option_resolver:
        class: Phlexible\Bundle\MetaSetBundle\Model\OptionResolver

    # acl providers
    phlexible_meta_set.acl_provider:
        class: Phlexible\Bundle\MetaSetBundle\AclProvider\MetaSetAclProvider
        public: false
        tags:
            - {name: phlexible_security.acl.provider}

    # asset providers
    phlexible_meta_set.asset_provider:
        class: Phlexible\Bundle\MetaSetBundle\AssetProvider\MetaSetAssetProvider
        public: false
        arguments: [@file_locator]
        tags:
            - {name: phlexible_gui.asset.provider}

    # event listeners
    phlexible_meta_set.listener.get_config:
        class: Phlexible\Bundle\MetaSetBundle\EventListener\GetConfigListener
        arguments: [%phlexible_meta_set.languages.default%, %phlexible_meta_set.languages.available%]
        tags:
            - {name: kernel.event_listener, event: phlexible_gui.get_config, method: onGetConfig}
