parameters:
    phlexible_meta_set.file_dir: %kernel.root_dir%/meta_sets
    phlexible_meta_set.languages.default: en
    phlexible_meta_set.languages.available: en,de
    phlexible_meta_set.suggest.seperator: ,

services:
    phlexible_meta_set.dumper.xml:
        class: Phlexible\Bundle\MetaSetBundle\Dumper\XmlDumper

    phlexible_meta_set.dumper:
        class: Phlexible\Bundle\MetaSetBundle\MetaSet\MetaSetDumper
        arguments: [@phlexible_meta_set.dumper.xml, %phlexible_meta_set.file_dir%]

    phlexible_meta_set.loader.xml:
        class: Phlexible\Bundle\MetaSetBundle\Loader\XmlLoader

    phlexible_meta_set.loader:
        class: Phlexible\Bundle\MetaSetBundle\MetaSet\MetaSetLoader
        arguments: [%kernel.bundles%, %phlexible_meta_set.file_dir%, [@phlexible_meta_set.loader.xml]]

    phlexible_meta_set.repository:
        class: Phlexible\Bundle\MetaSetBundle\MetaSet\MetaSetRepository
        arguments: [@phlexible_meta_set.loader, @phlexible_meta_set.dumper]

    phlexible_meta_set.data.repository:
        class: Phlexible\Bundle\MetaSetBundle\MetaData\MetaDataRepository
        arguments: [@connection_manager]

    # acl providers
    phlexible_meta_set.acl_provider:
        class: Phlexible\Bundle\MetaSetBundle\AclProvider\MetaSetAclProvider
        public: false
        tags:
            - {name: phlexible_security.acl.provider}

    # asset providers
    phlexible_meta_set.asset_provider:
        class: Phlexible\Bundle\MetaSetBundle\AssetProvider\MetaSetAssetProvider
        public: false
        arguments: [@file_locator]
        tags:
            - {name: phlexible_gui.asset.provider}

    # event listeners
    phlexible_meta_set.listener.get_config:
        class: Phlexible\Bundle\MetaSetBundle\EventListener\GetConfigListener
        arguments: [%phlexible_meta_set.languages.default%, %phlexible_meta_set.languages.available%]
        tags:
            - {name: kernel.event_listener, event: phlexible_gui.get_config, method: onGetConfig}
