parameters:
    phlexible_meta_set.languages.default: en
    phlexible_meta_set.languages.available: en,de
    phlexible_meta_set.suggest.seperator: ,

services:
    phlexible_meta_set.option_resolver:
        class: Phlexible\Bundle\MetaSetBundle\Model\OptionResolver

    # asset providers
    phlexible_meta_set.asset_provider:
        class: Phlexible\Bundle\MetaSetBundle\AssetProvider\MetaSetAssetProvider
        public: false
        tags:
            - {name: phlexible_gui.asset_provider}

    # event listeners
    phlexible_meta_set.listener.get_config:
        class: Phlexible\Bundle\MetaSetBundle\EventListener\GetConfigListener
        arguments: [%phlexible_meta_set.languages.default%, %phlexible_meta_set.languages.available%]
        tags:
            - {name: kernel.event_listener, event: phlexible_gui.get_config, method: onGetConfig}

    # role providers
    phlexible_meta_set.role_provider:
        class: Phlexible\Bundle\MetaSetBundle\RoleProvider\MetaSetRoleProvider
        public: false
        tags:
            - {name: phlexible_gui.role_provider}
