services:
    phlexible_elementtype.doctrine.viability_manager:
        class: Phlexible\Bundle\ElementtypeBundle\Doctrine\ViabilityManager
        arguments: [@doctrine.orm.entity_manager]
        public: false

