services:
    phlexible_elementtype.file.elementtype_manager:
        class: Phlexible\Component\Elementtype\File\ElementtypeManager
        arguments:
            - @phlexible_elementtype.file.loader.xml
            - @phlexible_elementtype.file.writer.xml
            - @validator
            - @event_dispatcher
        public: false

    phlexible_elementtype.file.loader.xml:
      class: Phlexible\Component\Elementtype\File\Loader\XmlLoader
      arguments: [@pattern_locator]

    phlexible_elementtype.file.writer.xml:
      class: Phlexible\Component\Elementtype\File\Writer\XmlWriter
      arguments: [@phlexible_elementtype.file.dumper.xml, "%kernel.root_dir%/Resources/elementtypes"]

    phlexible_elementtype.file.dumper.xml:
      class: Phlexible\Component\Elementtype\File\Dumper\XmlDumper
