services:
    phlexible_elementtype.file.elementtype_manager:
        class: Phlexible\Bundle\ElementtypeBundle\File\ElementtypeManager
        arguments:
            - @phlexible_elementtype.file.loader.xml
            - @phlexible_elementtype.file.dumper.xml
            - @event_dispatcher
            - @phlexible_message.message_poster
        public: false

    phlexible_elementtype.file.loader.xml:
      class: Phlexible\Bundle\ElementtypeBundle\File\Loader\XmlLoader
      arguments: [@pattern_locator]

    phlexible_elementtype.file.dumper.xml:
      class: Phlexible\Bundle\ElementtypeBundle\File\Loader\XmlDumper
