services:
    phlexible_elementtype.file.elementtype_manager:
        class: Phlexible\Component\Elementtype\File\ElementtypeManager
        arguments:
            - @phlexible_elementtype.file.puli_repository
            - @validator
            - @event_dispatcher
        public: false

    phlexible_elementtype.file.puli_repository:
      class: Phlexible\Component\Elementtype\File\PuliElementtypeRepository
      arguments:
        - @puli.discovery
        - @puli.repository
        - "xml"
        - "%kernel.root_dir%/Resources/elementtypes"
        - "/tipfinder/elementtypes"

    phlexible_elementtype.file.xml_dumper:
      class: Phlexible\Component\Elementtype\File\Dumper\XmlDumper
