services:
    phlexible_elementtype.service:
      class: Phlexible\Bundle\ElementtypeBundle\ElementtypeService
      arguments:
        - @phlexible_elementtype.repository
        - @phlexible_elementtype.version.repository
        - @phlexible_elementtype.structure.repository
        - @phlexible_elementtype.viability.manager

    phlexible_elementtype.viability.manager:
        class: Phlexible\Bundle\ElementtypeBundle\Viability\ViabilityManager
        arguments: [@connection_manager]
        public: false

    phlexible_elementtype.loader:
        class: Phlexible\Bundle\ElementtypeBundle\Elementtype\Loader\DatabaseLoader
        arguments: [@connection_manager]
        public: false

    phlexible_elementtype.repository:
        class: Phlexible\Bundle\ElementtypeBundle\Elementtype\ElementtypeRepository
        arguments: [@event_dispatcher, @phlexible_elementtype.loader, @phlexible_message.message_poster]
        public: false

    phlexible_elementtype.version.loader:
        class: Phlexible\Bundle\ElementtypeBundle\ElementtypeVersion\Loader\DatabaseLoader
        arguments: [@connection_manager]
        public: false

    phlexible_elementtype.version.repository:
        class: Phlexible\Bundle\ElementtypeBundle\ElementtypeVersion\ElementtypeVersionRepository
        arguments: [@event_dispatcher, @phlexible_elementtype.version.loader, @phlexible_message.message_poster]
        public: false

    phlexible_elementtype.structure.loader:
        class: Phlexible\Bundle\ElementtypeBundle\ElementtypeStructure\Loader\DatabaseLoader
        arguments: [@connection_manager]
        public: false

    phlexible_elementtype.structure.repository:
        class: Phlexible\Bundle\ElementtypeBundle\ElementtypeStructure\ElementtypeStructureRepository
        arguments: [@event_dispatcher, @phlexible_elementtype.structure.loader, @phlexible_message.message_poster]
        public: false

    # acl providers
    phlexible_elementtype.acl_provider:
        class: Phlexible\Bundle\ElementtypeBundle\AclProvider\ElementtypeAclProvider
        public: false
        tags:
            - {name: phlexible_security.acl.provider}

    # asset providers
    phlexible_elementtype.asset_provider:
        class: Phlexible\Bundle\ElementtypeBundle\AssetProvider\ElementtypeAssetProvider
        public: false
        arguments: [@file_locator]
        tags:
            - {name: phlexible_gui.asset.provider, priority: 100}

    # event listeners
    phlexible_elementtype.listener.apply_successor:
        class: Phlexible\Bundle\ElementtypeBundle\EventListener\ApplySuccessorListener
        arguments: [@connection_manager]
        tags:
            - {name: kernel.event_listener, event: phlexible_user.apply_successor, method: onApplySuccessor}

    phlexible_elementtype.listener.get_config:
        class: Phlexible\Bundle\ElementtypeBundle\EventListener\GetConfigListener
        arguments: [%phlexible_elementtype.field.suggest.seperator%]
        tags:
            - {name: kernel.event_listener, event: phlexible_gui.get_config, method: onGetConfig}

    phlexible_elementtype.listener.elementtype_usage:
        class: Phlexible\Bundle\ElementtypeBundle\EventListener\ElementtypeUsageListener
        arguments: [@connection_manager]
        tags:
            - {name: kernel.event_listener, event: phlexible_elementtype.usage, method: onElementtypeUsage}
