services:
    phlexible_elementtype.service:
      class: Phlexible\Bundle\ElementtypeBundle\ElementtypeService
      arguments:
        - @phlexible_elementtype.elementtype_manager
        - @phlexible_elementtype.elementtype_version_manager
        - @phlexible_elementtype.elementtype_structure_manager
        - @phlexible_elementtype.viability_manager

    # acl providers
    phlexible_elementtype.acl_provider:
        class: Phlexible\Bundle\ElementtypeBundle\AclProvider\ElementtypeAclProvider
        public: false
        tags:
            - {name: phlexible_security.acl.provider}

    # asset providers
    phlexible_elementtype.asset_provider:
        class: Phlexible\Bundle\ElementtypeBundle\AssetProvider\ElementtypeAssetProvider
        public: false
        arguments: [@file_locator]
        tags:
            - {name: phlexible_gui.asset.provider, priority: 100}

    # event listeners
    phlexible_elementtype.listener.apply_successor:
        class: Phlexible\Bundle\ElementtypeBundle\EventListener\ApplySuccessorListener
        arguments: [@doctrine.dbal.default_connection]
        tags:
            - {name: kernel.event_listener, event: phlexible_user.apply_successor, method: onApplySuccessor}

    phlexible_elementtype.listener.get_config:
        class: Phlexible\Bundle\ElementtypeBundle\EventListener\GetConfigListener
        arguments: [%phlexible_elementtype.field.suggest.seperator%]
        tags:
            - {name: kernel.event_listener, event: phlexible_gui.get_config, method: onGetConfig}

    phlexible_elementtype.listener.elementtype_usage:
        class: Phlexible\Bundle\ElementtypeBundle\EventListener\ElementtypeUsageListener
        arguments: [@doctrine.dbal.default_connection]
        tags:
            - {name: kernel.event_listener, event: phlexible_elementtype.usage, method: onElementtypeUsage}
