parameters:
    phlexible_security.mailer.validate.template: PhlexibleSecurityBundle:Reset:email.txt.twig
    phlexible_security.mailer.validate.from: %phlexible_gui.mail.from_email%

services:
    phlexible_security.mailer:
        class: Phlexible\Bundle\SecurityBundle\Mailer\Mailer
        arguments:
            - @twig
            - @mailer
            -
                validate: {template: %phlexible_security.mailer.validate.template%, from: %phlexible_security.mailer.validate.from%}

    # asset providers
    phlexible_security.asset_provider:
        class: Phlexible\Bundle\SecurityBundle\AssetProvider\SecurityAssetProvider
        public: false
        arguments: [@file_locator]
        tags:
            - {name: phlexible_gui.asset.provider}

    # listeners
    phlexible_security.listener.apply_successor:
        class: Phlexible\Bundle\SecurityBundle\EventListener\ApplySuccessorListener
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - {name: kernel.event_listener, event: phlexible_user.apply_successor, method: onApplySuccessor}

    phlexible_security.listener.request:
        class: Phlexible\Bundle\SecurityBundle\EventListener\RequestListener
        arguments: [@security.context, @router]
        tags:
            - {name: kernel.event_listener, event: kernel.request, method: onRequest, priority: -700}

    # views
    phlexible_security.view.login:
        class: Phlexible\Bundle\SecurityBundle\View\LoginView
        arguments: [@event_dispatcher]

    phlexible_security.view.logout:
        class: Phlexible\Bundle\SecurityBundle\View\LogoutView
        arguments: [@event_dispatcher]

    phlexible_security.view.validate_email:
        class: Phlexible\Bundle\SecurityBundle\View\ValidateEmailView
        arguments: [@event_dispatcher]

    phlexible_security.view.reset_password:
        class: Phlexible\Bundle\SecurityBundle\View\ResetPasswordView
        arguments: [@event_dispatcher]

    phlexible_security.view.force_password_change:
        class: Phlexible\Bundle\SecurityBundle\View\ForcePasswordChangeView
        arguments: [@event_dispatcher]

    # voters
    phlexible_security.authorisation.voter.zendacl:
        class: Phlexible\Bundle\SecurityBundle\Authorisation\Voter\ZendAclVoter
        public: false
        arguments: [@phlexible_security.acl]
        tags:
            - {name: security.voter}
